/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jassimp_Jassimp */

#ifndef _Included_jassimp_Jassimp
#define _Included_jassimp_Jassimp
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: BUILTIN */
/* Inaccessible static: s_wrapperProvider */
/*
 * Class:     jassimp_Jassimp
 * Method:    getErrorString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jassimp_Jassimp_getErrorString
  (JNIEnv *, jclass);

/*
 * Class:     jassimp_Jassimp
 * Method:    aiImportFile
 * Signature: (Ljava/lang/String;J)Ljassimp/AiScene;
 */
JNIEXPORT jobject JNICALL Java_jassimp_Jassimp_aiImportFile
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
