/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class assimp_Texture */

#ifndef _Included_assimp_Texture
#define _Included_assimp_Texture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     assimp_Texture
 * Method:    _NativeMapColorData
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_assimp_Texture__1NativeMapColorData
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
