/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class assimp_Importer */

#ifndef _Included_assimp_Importer
#define _Included_assimp_Importer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     assimp_Importer
 * Method:    _NativeInitContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_assimp_Importer__1NativeInitContext
  (JNIEnv *, jobject);

/*
 * Class:     assimp_Importer
 * Method:    _NativeFreeContext
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_assimp_Importer__1NativeFreeContext
  (JNIEnv *, jobject, jint);

/*
 * Class:     assimp_Importer
 * Method:    _NativeLoad
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_assimp_Importer__1NativeLoad
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
