/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class assimp_Mesh */

#ifndef _Included_assimp_Mesh
#define _Included_assimp_Mesh
#ifdef __cplusplus
extern "C" {
#endif
#undef assimp_Mesh_MAX_NUMBER_OF_TEXTURECOORDS
#define assimp_Mesh_MAX_NUMBER_OF_TEXTURECOORDS 4L
#undef assimp_Mesh_MAX_NUMBER_OF_COLOR_SETS
#define assimp_Mesh_MAX_NUMBER_OF_COLOR_SETS 4L
#undef assimp_Mesh_PF_POSITION
#define assimp_Mesh_PF_POSITION 1L
#undef assimp_Mesh_PF_NORMAL
#define assimp_Mesh_PF_NORMAL 2L
#undef assimp_Mesh_PF_TANGENTBITANGENT
#define assimp_Mesh_PF_TANGENTBITANGENT 4L
#undef assimp_Mesh_PF_BONES
#define assimp_Mesh_PF_BONES 8L
#undef assimp_Mesh_PF_VERTEXCOLOR
#define assimp_Mesh_PF_VERTEXCOLOR 4096L
#undef assimp_Mesh_PF_UVCOORD
#define assimp_Mesh_PF_UVCOORD 65536L
/*
 * Class:     assimp_Mesh
 * Method:    _NativeGetPresenceFlags
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeGetPresenceFlags
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     assimp_Mesh
 * Method:    _NativeGetNumVertices
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeGetNumVertices
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     assimp_Mesh
 * Method:    _NativeGetNumFaces
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeGetNumFaces
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     assimp_Mesh
 * Method:    _NativeGetNumBones
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeGetNumBones
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     assimp_Mesh
 * Method:    _NativeGetMaterialIndex
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeGetMaterialIndex
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     assimp_Mesh
 * Method:    _NativeGetNumUVComponents
 * Signature: (JJ[I)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeGetNumUVComponents
  (JNIEnv *, jobject, jlong, jlong, jintArray);

/*
 * Class:     assimp_Mesh
 * Method:    _NativeMapVertices
 * Signature: (JJ[F)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeMapVertices
  (JNIEnv *, jobject, jlong, jlong, jfloatArray);

/*
 * Class:     assimp_Mesh
 * Method:    _NativeMapNormals
 * Signature: (JJ[F)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeMapNormals
  (JNIEnv *, jobject, jlong, jlong, jfloatArray);

/*
 * Class:     assimp_Mesh
 * Method:    _NativeMapTangents
 * Signature: (JJ[F)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeMapTangents
  (JNIEnv *, jobject, jlong, jlong, jfloatArray);

/*
 * Class:     assimp_Mesh
 * Method:    _NativeMapBitangents
 * Signature: (JJ[F)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeMapBitangents
  (JNIEnv *, jobject, jlong, jlong, jfloatArray);

/*
 * Class:     assimp_Mesh
 * Method:    _NativeMapUVs
 * Signature: (JJI[F)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeMapUVs
  (JNIEnv *, jobject, jlong, jlong, jint, jfloatArray);

/*
 * Class:     assimp_Mesh
 * Method:    _NativeMapColors
 * Signature: (JJI[F)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeMapColors
  (JNIEnv *, jobject, jlong, jlong, jint, jfloatArray);

/*
 * Class:     assimp_Mesh
 * Method:    _NativeMapFaces
 * Signature: (JJ[I)I
 */
JNIEXPORT jint JNICALL Java_assimp_Mesh__1NativeMapFaces
  (JNIEnv *, jobject, jlong, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
