/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum aiAnimBehaviour {
  aiAnimBehaviour_DEFAULT = 0x0,
  aiAnimBehaviour_CONSTANT = 0x1,
  aiAnimBehaviour_LINEAR = 0x2,
  aiAnimBehaviour_REPEAT = 0x3
}
