/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class aiCamera : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal aiCamera(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(aiCamera obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~aiCamera() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Assimp_NETPINVOKE.delete_aiCamera(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public aiString mName {
    set {
      Assimp_NETPINVOKE.aiCamera_mName_set(swigCPtr, aiString.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Assimp_NETPINVOKE.aiCamera_mName_get(swigCPtr);
      aiString ret = (cPtr == IntPtr.Zero) ? null : new aiString(cPtr, false);
      return ret;
    } 
  }

  public aiVector3D mPosition {
    set {
      Assimp_NETPINVOKE.aiCamera_mPosition_set(swigCPtr, aiVector3D.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Assimp_NETPINVOKE.aiCamera_mPosition_get(swigCPtr);
      aiVector3D ret = (cPtr == IntPtr.Zero) ? null : new aiVector3D(cPtr, false);
      return ret;
    } 
  }

  public aiVector3D mUp {
    set {
      Assimp_NETPINVOKE.aiCamera_mUp_set(swigCPtr, aiVector3D.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Assimp_NETPINVOKE.aiCamera_mUp_get(swigCPtr);
      aiVector3D ret = (cPtr == IntPtr.Zero) ? null : new aiVector3D(cPtr, false);
      return ret;
    } 
  }

  public aiVector3D mLookAt {
    set {
      Assimp_NETPINVOKE.aiCamera_mLookAt_set(swigCPtr, aiVector3D.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Assimp_NETPINVOKE.aiCamera_mLookAt_get(swigCPtr);
      aiVector3D ret = (cPtr == IntPtr.Zero) ? null : new aiVector3D(cPtr, false);
      return ret;
    } 
  }

  public float mHorizontalFOV {
    set {
      Assimp_NETPINVOKE.aiCamera_mHorizontalFOV_set(swigCPtr, value);
    } 
    get {
      float ret = Assimp_NETPINVOKE.aiCamera_mHorizontalFOV_get(swigCPtr);
      return ret;
    } 
  }

  public float mClipPlaneNear {
    set {
      Assimp_NETPINVOKE.aiCamera_mClipPlaneNear_set(swigCPtr, value);
    } 
    get {
      float ret = Assimp_NETPINVOKE.aiCamera_mClipPlaneNear_get(swigCPtr);
      return ret;
    } 
  }

  public float mClipPlaneFar {
    set {
      Assimp_NETPINVOKE.aiCamera_mClipPlaneFar_set(swigCPtr, value);
    } 
    get {
      float ret = Assimp_NETPINVOKE.aiCamera_mClipPlaneFar_get(swigCPtr);
      return ret;
    } 
  }

  public float mAspect {
    set {
      Assimp_NETPINVOKE.aiCamera_mAspect_set(swigCPtr, value);
    } 
    get {
      float ret = Assimp_NETPINVOKE.aiCamera_mAspect_get(swigCPtr);
      return ret;
    } 
  }

  public aiCamera() : this(Assimp_NETPINVOKE.new_aiCamera(), true) {
  }

  public void GetCameraMatrix(aiMatrix4x4 arg0) {
    Assimp_NETPINVOKE.aiCamera_GetCameraMatrix(swigCPtr, aiMatrix4x4.getCPtr(arg0));
    if (Assimp_NETPINVOKE.SWIGPendingException.Pending) throw Assimp_NETPINVOKE.SWIGPendingException.Retrieve();
  }

}
