/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum aiLightSourceType {
  aiLightSource_UNDEFINED = 0x0,
  aiLightSource_DIRECTIONAL = 0x1,
  aiLightSource_POINT = 0x2,
  aiLightSource_SPOT = 0x3
}
