/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class aiMemoryInfo : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal aiMemoryInfo(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(aiMemoryInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~aiMemoryInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Assimp_NETPINVOKE.delete_aiMemoryInfo(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public aiMemoryInfo() : this(Assimp_NETPINVOKE.new_aiMemoryInfo(), true) {
  }

  public uint textures {
    set {
      Assimp_NETPINVOKE.aiMemoryInfo_textures_set(swigCPtr, value);
    } 
    get {
      uint ret = Assimp_NETPINVOKE.aiMemoryInfo_textures_get(swigCPtr);
      return ret;
    } 
  }

  public uint materials {
    set {
      Assimp_NETPINVOKE.aiMemoryInfo_materials_set(swigCPtr, value);
    } 
    get {
      uint ret = Assimp_NETPINVOKE.aiMemoryInfo_materials_get(swigCPtr);
      return ret;
    } 
  }

  public uint meshes {
    set {
      Assimp_NETPINVOKE.aiMemoryInfo_meshes_set(swigCPtr, value);
    } 
    get {
      uint ret = Assimp_NETPINVOKE.aiMemoryInfo_meshes_get(swigCPtr);
      return ret;
    } 
  }

  public uint nodes {
    set {
      Assimp_NETPINVOKE.aiMemoryInfo_nodes_set(swigCPtr, value);
    } 
    get {
      uint ret = Assimp_NETPINVOKE.aiMemoryInfo_nodes_get(swigCPtr);
      return ret;
    } 
  }

  public uint animations {
    set {
      Assimp_NETPINVOKE.aiMemoryInfo_animations_set(swigCPtr, value);
    } 
    get {
      uint ret = Assimp_NETPINVOKE.aiMemoryInfo_animations_get(swigCPtr);
      return ret;
    } 
  }

  public uint cameras {
    set {
      Assimp_NETPINVOKE.aiMemoryInfo_cameras_set(swigCPtr, value);
    } 
    get {
      uint ret = Assimp_NETPINVOKE.aiMemoryInfo_cameras_get(swigCPtr);
      return ret;
    } 
  }

  public uint lights {
    set {
      Assimp_NETPINVOKE.aiMemoryInfo_lights_set(swigCPtr, value);
    } 
    get {
      uint ret = Assimp_NETPINVOKE.aiMemoryInfo_lights_get(swigCPtr);
      return ret;
    } 
  }

  public uint total {
    set {
      Assimp_NETPINVOKE.aiMemoryInfo_total_set(swigCPtr, value);
    } 
    get {
      uint ret = Assimp_NETPINVOKE.aiMemoryInfo_total_get(swigCPtr);
      return ret;
    } 
  }

}
