/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum aiPropertyTypeInfo {
  aiPTI_Float = 0x1,
  aiPTI_String = 0x3,
  aiPTI_Integer = 0x4,
  aiPTI_Buffer = 0x5
}
