/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class aiQuatKeyVector : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IList<aiQuatKey>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal aiQuatKeyVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(aiQuatKeyVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~aiQuatKeyVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          AssimpPINVOKE.delete_aiQuatKeyVector(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public aiQuatKeyVector(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (aiQuatKey element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public aiQuatKey this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(aiQuatKey[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(aiQuatKey[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, aiQuatKey[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<aiQuatKey> System.Collections.Generic.IEnumerable<aiQuatKey>.GetEnumerator() {
    return new aiQuatKeyVectorEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new aiQuatKeyVectorEnumerator(this);
  }

  public aiQuatKeyVectorEnumerator GetEnumerator() {
    return new aiQuatKeyVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class aiQuatKeyVectorEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<aiQuatKey>
#endif
  {
    private aiQuatKeyVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public aiQuatKeyVectorEnumerator(aiQuatKeyVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public aiQuatKey Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (aiQuatKey)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    AssimpPINVOKE.aiQuatKeyVector_Clear(swigCPtr);
  }

  public void Add(aiQuatKey x) {
    AssimpPINVOKE.aiQuatKeyVector_Add(swigCPtr, aiQuatKey.getCPtr(x));
  }

  private uint size() {
    uint ret = AssimpPINVOKE.aiQuatKeyVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = AssimpPINVOKE.aiQuatKeyVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    AssimpPINVOKE.aiQuatKeyVector_reserve(swigCPtr, n);
  }

  public aiQuatKeyVector() : this(AssimpPINVOKE.new_aiQuatKeyVector__SWIG_0(), true) {
  }

  public aiQuatKeyVector(aiQuatKeyVector other) : this(AssimpPINVOKE.new_aiQuatKeyVector__SWIG_1(aiQuatKeyVector.getCPtr(other)), true) {
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public aiQuatKeyVector(int capacity) : this(AssimpPINVOKE.new_aiQuatKeyVector__SWIG_2(capacity), true) {
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  private aiQuatKey getitemcopy(int index) {
    IntPtr cPtr = AssimpPINVOKE.aiQuatKeyVector_getitemcopy(swigCPtr, index);
    aiQuatKey ret = (cPtr == IntPtr.Zero) ? null : new aiQuatKey(cPtr, false);
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private aiQuatKey getitem(int index) {
    IntPtr cPtr = AssimpPINVOKE.aiQuatKeyVector_getitem(swigCPtr, index);
    aiQuatKey ret = (cPtr == IntPtr.Zero) ? null : new aiQuatKey(cPtr, false);
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, aiQuatKey val) {
    AssimpPINVOKE.aiQuatKeyVector_setitem(swigCPtr, index, aiQuatKey.getCPtr(val));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(aiQuatKeyVector values) {
    AssimpPINVOKE.aiQuatKeyVector_AddRange(swigCPtr, aiQuatKeyVector.getCPtr(values));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public aiQuatKeyVector GetRange(int index, int count) {
    IntPtr cPtr = AssimpPINVOKE.aiQuatKeyVector_GetRange(swigCPtr, index, count);
    aiQuatKeyVector ret = (cPtr == IntPtr.Zero) ? null : new aiQuatKeyVector(cPtr, true);
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, aiQuatKey x) {
    AssimpPINVOKE.aiQuatKeyVector_Insert(swigCPtr, index, aiQuatKey.getCPtr(x));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, aiQuatKeyVector values) {
    AssimpPINVOKE.aiQuatKeyVector_InsertRange(swigCPtr, index, aiQuatKeyVector.getCPtr(values));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    AssimpPINVOKE.aiQuatKeyVector_RemoveAt(swigCPtr, index);
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    AssimpPINVOKE.aiQuatKeyVector_RemoveRange(swigCPtr, index, count);
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public static aiQuatKeyVector Repeat(aiQuatKey value, int count) {
    IntPtr cPtr = AssimpPINVOKE.aiQuatKeyVector_Repeat(aiQuatKey.getCPtr(value), count);
    aiQuatKeyVector ret = (cPtr == IntPtr.Zero) ? null : new aiQuatKeyVector(cPtr, true);
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    AssimpPINVOKE.aiQuatKeyVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    AssimpPINVOKE.aiQuatKeyVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, aiQuatKeyVector values) {
    AssimpPINVOKE.aiQuatKeyVector_SetRange(swigCPtr, index, aiQuatKeyVector.getCPtr(values));
    if (AssimpPINVOKE.SWIGPendingException.Pending) throw AssimpPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(aiQuatKey value) {
    bool ret = AssimpPINVOKE.aiQuatKeyVector_Contains(swigCPtr, aiQuatKey.getCPtr(value));
    return ret;
  }

  public int IndexOf(aiQuatKey value) {
    int ret = AssimpPINVOKE.aiQuatKeyVector_IndexOf(swigCPtr, aiQuatKey.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(aiQuatKey value) {
    int ret = AssimpPINVOKE.aiQuatKeyVector_LastIndexOf(swigCPtr, aiQuatKey.getCPtr(value));
    return ret;
  }

  public bool Remove(aiQuatKey value) {
    bool ret = AssimpPINVOKE.aiQuatKeyVector_Remove(swigCPtr, aiQuatKey.getCPtr(value));
    return ret;
  }

}
