/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class aiString : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal aiString(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(aiString obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~aiString() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Assimp_NETPINVOKE.delete_aiString(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public aiString() : this(Assimp_NETPINVOKE.new_aiString__SWIG_0(), true) {
  }

  public aiString(aiString rOther) : this(Assimp_NETPINVOKE.new_aiString__SWIG_1(aiString.getCPtr(rOther)), true) {
    if (Assimp_NETPINVOKE.SWIGPendingException.Pending) throw Assimp_NETPINVOKE.SWIGPendingException.Retrieve();
  }

  public aiString(string pString) : this(Assimp_NETPINVOKE.new_aiString__SWIG_2(pString), true) {
    if (Assimp_NETPINVOKE.SWIGPendingException.Pending) throw Assimp_NETPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Set(string pString) {
    Assimp_NETPINVOKE.aiString_Set__SWIG_0(swigCPtr, pString);
    if (Assimp_NETPINVOKE.SWIGPendingException.Pending) throw Assimp_NETPINVOKE.SWIGPendingException.Retrieve();
  }

  public aiString __set__(string sz) {
    aiString ret = new aiString(Assimp_NETPINVOKE.aiString___set____SWIG_0(swigCPtr, sz), false);
    return ret;
  }

  public bool __equal__(aiString other) {
    bool ret = Assimp_NETPINVOKE.aiString___equal__(swigCPtr, aiString.getCPtr(other));
    if (Assimp_NETPINVOKE.SWIGPendingException.Pending) throw Assimp_NETPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool __nequal__(aiString other) {
    bool ret = Assimp_NETPINVOKE.aiString___nequal__(swigCPtr, aiString.getCPtr(other));
    if (Assimp_NETPINVOKE.SWIGPendingException.Pending) throw Assimp_NETPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Append(string app) {
    Assimp_NETPINVOKE.aiString_Append(swigCPtr, app);
  }

  public void Clear() {
    Assimp_NETPINVOKE.aiString_Clear(swigCPtr);
  }

  public uint length {
    set {
      Assimp_NETPINVOKE.aiString_length_set(swigCPtr, value);
    } 
    get {
      uint ret = Assimp_NETPINVOKE.aiString_length_get(swigCPtr);
      return ret;
    } 
  }

  public string data {
    set {
      Assimp_NETPINVOKE.aiString_data_set(swigCPtr, value);
    } 
    get {
      string ret = Assimp_NETPINVOKE.aiString_data_get(swigCPtr);
      return ret;
    } 
  }

}
