/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class SWIGTYPE_p_f_p_aiFile_size_t_enum_aiOrigin__aiReturn {
  private HandleRef swigCPtr;

  internal SWIGTYPE_p_f_p_aiFile_size_t_enum_aiOrigin__aiReturn(IntPtr cPtr, bool futureUse) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  protected SWIGTYPE_p_f_p_aiFile_size_t_enum_aiOrigin__aiReturn() {
    swigCPtr = new HandleRef(null, IntPtr.Zero);
  }

  internal static HandleRef getCPtr(SWIGTYPE_p_f_p_aiFile_size_t_enum_aiOrigin__aiReturn obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
}
