/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class assimp_Importer_DefaultIOSystem */

#ifndef _Included_assimp_Importer_DefaultIOSystem
#define _Included_assimp_Importer_DefaultIOSystem
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
