//---------------------------------------------------------------------------

#include <vcl.h>
#pragma hdrstop
USERES("workspace.res");
USEUNIT("..\..\code\XFileParser.cpp");
USEUNIT("..\..\code\3DSLoader.cpp");
USEUNIT("..\..\code\ACLoader.cpp");
USEUNIT("..\..\code\aiAssert.cpp");
USEUNIT("..\..\code\ASELoader.cpp");
USEUNIT("..\..\code\ASEParser.cpp");
USEUNIT("..\..\code\Assimp.cpp");
USEUNIT("..\..\code\BaseImporter.cpp");
USEUNIT("..\..\code\BaseProcess.cpp");
USEUNIT("..\..\code\CalcTangentsProcess.cpp");
USEUNIT("..\..\code\ConvertToLHProcess.cpp");
USEUNIT("..\..\code\DefaultIOStream.cpp");
USEUNIT("..\..\code\DefaultIOSystem.cpp");
USEUNIT("..\..\code\DefaultLogger.cpp");
USEUNIT("..\..\code\DXFLoader.cpp");
USEUNIT("..\..\code\FixNormalsStep.cpp");
USEUNIT("..\..\code\GenFaceNormalsProcess.cpp");
USEUNIT("..\..\code\GenVertexNormalsProcess.cpp");
USEUNIT("..\..\code\HMPLoader.cpp");
USEUNIT("..\..\code\Importer.cpp");
USEUNIT("..\..\code\ImproveCacheLocality.cpp");
USEUNIT("..\..\code\JoinVerticesProcess.cpp");
USEUNIT("..\..\code\LimitBoneWeightsProcess.cpp");
USEUNIT("..\..\code\LWOBLoader.cpp");
USEUNIT("..\..\code\LWOLoader.cpp");
USEUNIT("..\..\code\LWOMaterial.cpp");
USEUNIT("..\..\code\MaterialSystem.cpp");
USEUNIT("..\..\code\MD2Loader.cpp");
USEUNIT("..\..\code\MD3Loader.cpp");
USEUNIT("..\..\code\MD5Loader.cpp");
USEUNIT("..\..\code\MD5Parser.cpp");
USEUNIT("..\..\code\MDCLoader.cpp");
USEUNIT("..\..\code\MDLLoader.cpp");
USEUNIT("..\..\code\MDLMaterialLoader.cpp");
USEUNIT("..\..\code\MDRLoader.cpp");
USEUNIT("..\..\code\NFFLoader.cpp");
USEUNIT("..\..\code\ObjFileImporter.cpp");
USEUNIT("..\..\code\ObjFileMtlImporter.cpp");
USEUNIT("..\..\code\ObjFileParser.cpp");
USEUNIT("..\..\code\OFFLoader.cpp");
USEUNIT("..\..\code\OptimizeGraphProcess.cpp");
USEUNIT("..\..\code\PlyLoader.cpp");
USEUNIT("..\..\code\PlyParser.cpp");
USEUNIT("..\..\code\PretransformVertices.cpp");
USEUNIT("..\..\code\RawLoader.cpp");
USEUNIT("..\..\code\RemoveComments.cpp");
USEUNIT("..\..\code\RemoveRedundantMaterials.cpp");
USEUNIT("..\..\code\RemoveVCProcess.cpp");
USEUNIT("..\..\code\SGSpatialSort.cpp");
USEUNIT("..\..\code\SMDLoader.cpp");
USEUNIT("..\..\code\SortByPTypeProcess.cpp");
USEUNIT("..\..\code\SpatialSort.cpp");
USEUNIT("..\..\code\SplitLargeMeshes.cpp");
USEUNIT("..\..\code\StandardShapes.cpp");
USEUNIT("..\..\code\STLLoader.cpp");
USEUNIT("..\..\code\TextureTransform.cpp");
USEUNIT("..\..\code\TriangulateProcess.cpp");
USEUNIT("..\..\code\ValidateDataStructure.cpp");
USEUNIT("..\..\code\VertexTriangleAdjacency.cpp");
USEUNIT("..\..\code\XFileImporter.cpp");
USEUNIT("..\..\code\3DSConverter.cpp");
USE("..\..\code\SmoothingGroups.inl", File);
USE("..\..\code\3DSLoader.h", File);
USE("..\..\code\ACLoader.h", File);
USE("..\..\code\ASELoader.h", File);
USE("..\..\code\ASEParser.h", File);
USE("..\..\code\BaseImporter.h", File);
USE("..\..\code\BaseProcess.h", File);
USE("..\..\code\ByteSwap.h", File);
USE("..\..\code\CalcTangentsProcess.h", File);
USE("..\..\code\ConvertToLHProcess.h", File);
USE("..\..\code\DefaultIOStream.h", File);
USE("..\..\code\DefaultIOSystem.h", File);
USE("..\..\code\DXFLoader.h", File);
USE("..\..\code\FaceEdgeAdjacency.h", File);
USE("..\..\code\fast_atof.h", File);
USE("..\..\code\FileLogStream.h", File);
USE("..\..\code\FixNormalsStep.h", File);
USE("..\..\code\GenericProperty.h", File);
USE("..\..\code\GenFaceNormalsProcess.h", File);
USE("..\..\code\GenVertexNormalsProcess.h", File);
USE("..\..\code\HalfLifeFileData.h", File);
USE("..\..\code\Hash.h", File);
USE("..\..\code\HMPFileData.h", File);
USE("..\..\code\HMPLoader.h", File);
USE("..\..\code\IFF.h", File);
USE("..\..\code\ImproveCacheLocality.h", File);
USE("..\..\code\JoinVerticesProcess.h", File);
USE("..\..\code\LimitBoneWeightsProcess.h", File);
USE("..\..\code\LWOFileData.h", File);
USE("..\..\code\LWOLoader.h", File);
USE("..\..\code\MaterialSystem.h", File);
USE("..\..\code\MD2FileData.h", File);
USE("..\..\code\MD2Loader.h", File);
USE("..\..\code\MD2NormalTable.h", File);
USE("..\..\code\MD3FileData.h", File);
USE("..\..\code\MD3Loader.h", File);
USE("..\..\code\MD5Loader.h", File);
USE("..\..\code\MD5Parser.h", File);
USE("..\..\code\MDCFileData.h", File);
USE("..\..\code\MDCLoader.h", File);
USE("..\..\code\MDCNormalTable.h", File);
USE("..\..\code\MDLDefaultColorMap.h", File);
USE("..\..\code\MDLFileData.h", File);
USE("..\..\code\MDLLoader.h", File);
USE("..\..\code\MDRFileData.h", File);
USE("..\..\code\MDRLoader.h", File);
USE("..\..\code\NFFLoader.h", File);
USE("..\..\code\ObjFileData.h", File);
USE("..\..\code\ObjFileImporter.h", File);
USE("..\..\code\ObjFileMtlImporter.h", File);
USE("..\..\code\ObjFileParser.h", File);
USE("..\..\code\ObjTools.h", File);
USE("..\..\code\OFFLoader.h", File);
USE("..\..\code\OptimizeGraphProcess.h", File);
USE("..\..\code\ParsingUtils.h", File);
USE("..\..\code\PlyLoader.h", File);
USE("..\..\code\PlyParser.h", File);
USE("..\..\code\PretransformVertices.h", File);
USE("..\..\code\ProcessHelper.h", File);
USE("..\..\code\qnan.h", File);
USE("..\..\code\RawLoader.h", File);
USE("..\..\code\RemoveComments.h", File);
USE("..\..\code\RemoveRedundantMaterials.h", File);
USE("..\..\code\RemoveVCProcess.h", File);
USE("..\..\code\SGSpatialSort.h", File);
USE("..\..\code\SMDLoader.h", File);
USE("..\..\code\SmoothingGroups.h", File);
USE("..\..\code\SortByPTypeProcess.h", File);
USE("..\..\code\SpatialSort.h", File);
USE("..\..\code\SplitLargeMeshes.h", File);
USE("..\..\code\StandardShapes.h", File);
USE("..\..\code\STLLoader.h", File);
USE("..\..\code\StringComparison.h", File);
USE("..\..\code\TextureTransform.h", File);
USE("..\..\code\TriangulateProcess.h", File);
USE("..\..\code\ValidateDataStructure.h", File);
USE("..\..\code\VertexTriangleAdjacency.h", File);
USE("..\..\code\Win32DebugLogStream.h", File);
USE("..\..\code\XFileHelper.h", File);
USE("..\..\code\XFileImporter.h", File);
USE("..\..\code\XFileParser.h", File);
USE("..\..\code\3DSHelper.h", File);
USE("..\..\include\NullLogger.h", File);
USE("..\..\include\aiAssert.h", File);
USE("..\..\include\aiConfig.h", File);
USE("..\..\include\aiDefines.h", File);
USE("..\..\include\aiFileIO.h", File);
USE("..\..\include\aiMaterial.h", File);
USE("..\..\include\aiMaterial.inl", File);
USE("..\..\include\aiMatrix3x3.h", File);
USE("..\..\include\aiMatrix3x3.inl", File);
USE("..\..\include\aiMatrix4x4.~inl", File);
USE("..\..\include\aiMatrix4x4.h", File);
USE("..\..\include\aiMatrix4x4.inl", File);
USE("..\..\include\aiMesh.h", File);
USE("..\..\include\aiPostProcess.h", File);
USE("..\..\include\aiQuaternion.h", File);
USE("..\..\include\aiScene.h", File);
USE("..\..\include\aiSceneEntities.h", File);
USE("..\..\include\aiTexture.h", File);
USE("..\..\include\aiTypes.h", File);
USE("..\..\include\aiVector3D.h", File);
USE("..\..\include\aiVector3D.inl", File);
USE("..\..\include\assimp.h", File);
USE("..\..\include\assimp.hpp", File);
USE("..\..\include\DefaultLogger.h", File);
USE("..\..\include\IOStream.h", File);
USE("..\..\include\IOSystem.h", File);
USE("..\..\include\Logger.h", File);
USE("..\..\include\LogStream.h", File);
USE("..\..\include\aiAnim.h", File);
USE("..\..\include\Compiler\poppack1.h", File);
USE("..\..\include\Compiler\pushpack1.h", File);
//---------------------------------------------------------------------------
WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int)
{
        try
        {
                 Application->Initialize();
                 Application->Run();
        }
        catch (Exception &exception)
        {
                 Application->ShowException(&exception);
        }
        return 0;
}
//---------------------------------------------------------------------------
