site_name: TinyUSDZ 

theme:
  name: material
  palette:
    scheme: slate

markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      macro-file: macros.tex
  - admonition
