unit aiConfig;

interface

// The AI_CONFIG_XXX constants are the property names accepted by the aiSetImportPropertyXXX
// functions, and the other constants their documented defaults

const AI_CONFIG_GLOB_MEASURE_TIME = 'GLOB_MEASURE_TIME';
const AI_CONFIG_IMPORT_NO_SKELETON_MESHES = 'IMPORT_NO_SKELETON_MESHES';
const AI_CONFIG_PP_SBBC_MAX_BONES = 'PP_SBBC_MAX_BONES';
const AI_SBBC_DEFAULT_MAX_BONES = 60;
const AI_CONFIG_PP_CT_MAX_SMOOTHING_ANGLE = 'PP_CT_MAX_SMOOTHING_ANGLE';
const AI_CONFIG_PP_CT_TEXTURE_CHANNEL_INDEX = 'PP_CT_TEXTURE_CHANNEL_INDEX';
const AI_CONFIG_PP_GSN_MAX_SMOOTHING_ANGLE = 'PP_GSN_MAX_SMOOTHING_ANGLE';
const AI_CONFIG_IMPORT_MDL_COLORMAP = 'IMPORT_MDL_COLORMAP';
const AI_CONFIG_PP_RRM_EXCLUDE_LIST = 'PP_RRM_EXCLUDE_LIST';
const AI_CONFIG_PP_PTV_KEEP_HIERARCHY = 'PP_PTV_KEEP_HIERARCHY';
const AI_CONFIG_PP_PTV_NORMALIZE = 'PP_PTV_NORMALIZE';
const AI_CONFIG_PP_PTV_ADD_ROOT_TRANSFORMATION = 'PP_PTV_ADD_ROOT_TRANSFORMATION';
const AI_CONFIG_PP_PTV_ROOT_TRANSFORMATION = 'PP_PTV_ROOT_TRANSFORMATION';
const AI_CONFIG_CHECK_IDENTITY_MATRIX_EPSILON = 'CHECK_IDENTITY_MATRIX_EPSILON';
const AI_CONFIG_CHECK_IDENTITY_MATRIX_EPSILON_DEFAULT = 10e-3;
const AI_CONFIG_PP_FD_REMOVE = 'PP_FD_REMOVE';
const AI_CONFIG_PP_FD_CHECKAREA = 'PP_FD_CHECKAREA';
const AI_CONFIG_PP_OG_EXCLUDE_LIST = 'PP_OG_EXCLUDE_LIST';
const AI_CONFIG_PP_SLM_TRIANGLE_LIMIT = 'PP_SLM_TRIANGLE_LIMIT';
const AI_SLM_DEFAULT_MAX_TRIANGLES = 1000000;
const AI_CONFIG_PP_SLM_VERTEX_LIMIT = 'PP_SLM_VERTEX_LIMIT';
const AI_SLM_DEFAULT_MAX_VERTICES = 1000000;
const AI_CONFIG_PP_LBW_MAX_WEIGHTS = 'PP_LBW_MAX_WEIGHTS';
const AI_LMW_MAX_WEIGHTS = $4;
const AI_CONFIG_PP_DB_THRESHOLD = 'PP_DB_THRESHOLD';
const AI_DEBONE_THRESHOLD = 1.0;
const AI_CONFIG_PP_DB_ALL_OR_NONE = 'PP_DB_ALL_OR_NONE';
const AI_CONFIG_PP_ICL_PTCACHE_SIZE = 'PP_ICL_PTCACHE_SIZE';
const AI_CONFIG_PP_RVC_FLAGS = 'PP_RVC_FLAGS';
const AI_CONFIG_PP_SBP_REMOVE = 'PP_SBP_REMOVE';
const AI_CONFIG_PP_FID_ANIM_ACCURACY = 'PP_FID_ANIM_ACCURACY';
const AI_CONFIG_PP_FID_IGNORE_TEXTURECOORDS = 'PP_FID_IGNORE_TEXTURECOORDS';
const AI_UVTRAFO_SCALING = $1;
const AI_UVTRAFO_ROTATION = $2;
const AI_UVTRAFO_TRANSLATION = $4;
const AI_UVTRAFO_ALL = AI_UVTRAFO_SCALING or AI_UVTRAFO_ROTATION or AI_UVTRAFO_TRANSLATION;
const AI_CONFIG_PP_TUV_EVALUATE = 'PP_TUV_EVALUATE';
const AI_CONFIG_FAVOUR_SPEED = 'FAVOUR_SPEED';
const AI_CONFIG_IMPORT_SCHEMA_DOCUMENT_PROVIDER = 'IMPORT_SCHEMA_DOCUMENT_PROVIDER';
const AI_CONFIG_IMPORT_FBX_READ_ALL_GEOMETRY_LAYERS = 'IMPORT_FBX_READ_ALL_GEOMETRY_LAYERS';
const AI_CONFIG_IMPORT_FBX_READ_ALL_MATERIALS = 'IMPORT_FBX_READ_ALL_MATERIALS';
const AI_CONFIG_IMPORT_FBX_READ_MATERIALS = 'IMPORT_FBX_READ_MATERIALS';
const AI_CONFIG_IMPORT_FBX_READ_TEXTURES = 'IMPORT_FBX_READ_TEXTURES';
const AI_CONFIG_IMPORT_FBX_READ_CAMERAS = 'IMPORT_FBX_READ_CAMERAS';
const AI_CONFIG_IMPORT_FBX_READ_LIGHTS = 'IMPORT_FBX_READ_LIGHTS';
const AI_CONFIG_IMPORT_FBX_READ_ANIMATIONS = 'IMPORT_FBX_READ_ANIMATIONS';
const AI_CONFIG_IMPORT_FBX_READ_WEIGHTS = 'IMPORT_FBX_READ_WEIGHTS';
const AI_CONFIG_IMPORT_FBX_STRICT_MODE = 'IMPORT_FBX_STRICT_MODE';
const AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS = 'IMPORT_FBX_PRESERVE_PIVOTS';
const AI_CONFIG_IMPORT_FBX_OPTIMIZE_EMPTY_ANIMATION_CURVES = 'IMPORT_FBX_OPTIMIZE_EMPTY_ANIMATION_CURVES';
const AI_CONFIG_IMPORT_FBX_EMBEDDED_TEXTURES_LEGACY_NAMING = 'AI_CONFIG_IMPORT_FBX_EMBEDDED_TEXTURES_LEGACY_NAMING';
const AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES = 'AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES';
const AI_CONFIG_FBX_CONVERT_TO_M = 'AI_CONFIG_FBX_CONVERT_TO_M';
const AI_CONFIG_IMPORT_FBX_IGNORE_UP_DIRECTION = 'AI_CONFIG_IMPORT_FBX_IGNORE_UP_DIRECTION';
const AI_CONFIG_FBX_USE_SKELETON_BONE_CONTAINER = 'AI_CONFIG_FBX_USE_SKELETON_BONE_CONTAINER';
const AI_CONFIG_IMPORT_GLOBAL_KEYFRAME = 'IMPORT_GLOBAL_KEYFRAME';
const AI_CONFIG_IMPORT_MD3_KEYFRAME = 'IMPORT_MD3_KEYFRAME';
const AI_CONFIG_IMPORT_MD2_KEYFRAME = 'IMPORT_MD2_KEYFRAME';
const AI_CONFIG_IMPORT_MDL_KEYFRAME = 'IMPORT_MDL_KEYFRAME';
const AI_CONFIG_IMPORT_MDC_KEYFRAME = 'IMPORT_MDC_KEYFRAME';
const AI_CONFIG_IMPORT_SMD_KEYFRAME = 'IMPORT_SMD_KEYFRAME';
const AI_CONFIG_IMPORT_UNREAL_KEYFRAME = 'IMPORT_UNREAL_KEYFRAME';
const AI_CONFIG_IMPORT_MDL_HL1_READ_ANIMATIONS = 'IMPORT_MDL_HL1_READ_ANIMATIONS';
const AI_CONFIG_IMPORT_MDL_HL1_READ_ANIMATION_EVENTS = 'IMPORT_MDL_HL1_READ_ANIMATION_EVENTS';
const AI_CONFIG_IMPORT_MDL_HL1_TRANSFORM_COORD_SYSTEM = 'TRANSFORM COORDSYSTEM FOR HS! MODELS';
const AI_CONFIG_IMPORT_MDL_HL1_READ_BLEND_CONTROLLERS = 'IMPORT_MDL_HL1_READ_BLEND_CONTROLLERS';
const AI_CONFIG_IMPORT_MDL_HL1_READ_SEQUENCE_TRANSITIONS = 'IMPORT_MDL_HL1_READ_SEQUENCE_TRANSITIONS';
const AI_CONFIG_IMPORT_MDL_HL1_READ_ATTACHMENTS = 'IMPORT_MDL_HL1_READ_ATTACHMENTS';
const AI_CONFIG_IMPORT_MDL_HL1_READ_BONE_CONTROLLERS = 'IMPORT_MDL_HL1_READ_BONE_CONTROLLERS';
const AI_CONFIG_IMPORT_MDL_HL1_READ_HITBOXES = 'IMPORT_MDL_HL1_READ_HITBOXES';
const AI_CONFIG_IMPORT_MDL_HL1_READ_MISC_GLOBAL_INFO = 'IMPORT_MDL_HL1_READ_MISC_GLOBAL_INFO';
const AI_CONFIG_IMPORT_SMD_LOAD_ANIMATION_LIST = 'IMPORT_SMD_LOAD_ANIMATION_LIST';
const AI_CONFIG_IMPORT_AC_SEPARATE_BFCULL = 'IMPORT_AC_SEPARATE_BFCULL';
const AI_CONFIG_IMPORT_AC_EVAL_SUBDIVISION = 'IMPORT_AC_EVAL_SUBDIVISION';
const AI_CONFIG_IMPORT_UNREAL_HANDLE_FLAGS = 'UNREAL_HANDLE_FLAGS';
const AI_CONFIG_IMPORT_TER_MAKE_UVS = 'IMPORT_TER_MAKE_UVS';
const AI_CONFIG_IMPORT_ASE_RECONSTRUCT_NORMALS = 'IMPORT_ASE_RECONSTRUCT_NORMALS';
const AI_CONFIG_IMPORT_MD3_HANDLE_MULTIPART = 'IMPORT_MD3_HANDLE_MULTIPART';
const AI_CONFIG_IMPORT_MD3_SKIN_NAME = 'IMPORT_MD3_SKIN_NAME';
const AI_CONFIG_IMPORT_MD3_LOAD_SHADERS = 'IMPORT_MD3_LOAD_SHADERS';
const AI_CONFIG_IMPORT_MD3_SHADER_SRC = 'IMPORT_MD3_SHADER_SRC';
const AI_CONFIG_IMPORT_LWO_ONE_LAYER_ONLY = 'IMPORT_LWO_ONE_LAYER_ONLY';
const AI_CONFIG_IMPORT_MD5_NO_ANIM_AUTOLOAD = 'IMPORT_MD5_NO_ANIM_AUTOLOAD';
const AI_CONFIG_IMPORT_LWS_ANIM_START = 'IMPORT_LWS_ANIM_START';
const AI_CONFIG_IMPORT_LWS_ANIM_END = 'IMPORT_LWS_ANIM_END';
const AI_CONFIG_IMPORT_IRR_ANIM_FPS = 'IMPORT_IRR_ANIM_FPS';
const AI_CONFIG_IMPORT_OGRE_MATERIAL_FILE = 'IMPORT_OGRE_MATERIAL_FILE';
const AI_CONFIG_IMPORT_OGRE_TEXTURETYPE_FROM_FILENAME = 'IMPORT_OGRE_TEXTURETYPE_FROM_FILENAME';
const AI_CONFIG_ANDROID_JNI_ASSIMP_MANAGER_SUPPORT = 'AI_CONFIG_ANDROID_JNI_ASSIMP_MANAGER_SUPPORT';
const AI_CONFIG_IMPORT_IFC_SKIP_SPACE_REPRESENTATIONS = 'IMPORT_IFC_SKIP_SPACE_REPRESENTATIONS';
const AI_CONFIG_IMPORT_IFC_CUSTOM_TRIANGULATION = 'IMPORT_IFC_CUSTOM_TRIANGULATION';
const AI_CONFIG_IMPORT_IFC_SMOOTHING_ANGLE = 'IMPORT_IFC_SMOOTHING_ANGLE';
const AI_IMPORT_IFC_DEFAULT_SMOOTHING_ANGLE = 10.0;
const AI_CONFIG_IMPORT_IFC_CYLINDRICAL_TESSELLATION = 'IMPORT_IFC_CYLINDRICAL_TESSELLATION';
const AI_IMPORT_IFC_DEFAULT_CYLINDRICAL_TESSELLATION = 32;
const AI_CONFIG_IMPORT_COLLADA_IGNORE_UP_DIRECTION = 'IMPORT_COLLADA_IGNORE_UP_DIRECTION';
const AI_CONFIG_IMPORT_COLLADA_IGNORE_UNIT_SIZE = 'IMPORT_COLLADA_IGNORE_UNIT_SIZE';
const AI_CONFIG_IMPORT_COLLADA_USE_COLLADA_NAMES = 'IMPORT_COLLADA_USE_COLLADA_NAMES';
const AI_CONFIG_EXPORT_XFILE_64BIT = 'EXPORT_XFILE_64BIT';
const AI_CONFIG_EXPORT_POINT_CLOUDS = 'EXPORT_POINT_CLOUDS';
const AI_CONFIG_USE_GLTF_PBR_SPECULAR_GLOSSINESS = 'USE_GLTF_PBR_SPECULAR_GLOSSINESS';
const AI_CONFIG_EXPORT_GLTF_UNLIMITED_SKINNING_BONES_PER_VERTEX = 'USE_UNLIMITED_BONES_PER VERTEX';
const AI_CONFIG_EXPORT_FBX_TRANSPARENCY_FACTOR_REFER_TO_OPACITY = 'EXPORT_FBX_TRANSPARENCY_FACTOR_REFER_TO_OPACITY';
const AI_CONFIG_EXPORT_BLOB_NAME = 'EXPORT_BLOB_NAME';
const AI_CONFIG_GLOBAL_SCALE_FACTOR_KEY = 'GLOBAL_SCALE_FACTOR';
const AI_CONFIG_GLOBAL_SCALE_FACTOR_DEFAULT = 1.0;
const AI_CONFIG_APP_SCALE_KEY = 'APP_SCALE_FACTOR';
const aiComponent_NORMALS = $2;
const aiComponent_TANGENTS_AND_BITANGENTS = $4;
const aiComponent_COLORS = $8;
const aiComponent_TEXCOORDS = $10;
const aiComponent_BONEWEIGHTS = $20;
const aiComponent_ANIMATIONS = $40;
const aiComponent_TEXTURES = $80;
const aiComponent_LIGHTS = $100;
const aiComponent_CAMERAS = $200;
const aiComponent_MESHES = $400;
const aiComponent_MATERIALS = $800;

// aiComponent_COLORSn and aiComponent_TEXCOORDSn are macros in C
function aiComponent_COLORSn(n: Cardinal): Cardinal;
function aiComponent_TEXCOORDSn(n: Cardinal): Cardinal;

implementation

function aiComponent_COLORSn(n: Cardinal): Cardinal;
begin
   result := Cardinal(1) shl (n+20);
end;

function aiComponent_TEXCOORDSn(n: Cardinal): Cardinal;
begin
   result := Cardinal(1) shl (n+25);
end;

end.