#include "openskp/dxf_export.hpp"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <functional>
#include <iomanip>
#include <map>
#include <sstream>
#include <stdexcept>
#include <string>
#include <tuple>
#include <vector>

namespace openskp {

static std::string sanitize_layer_name(const std::string& name) {
  if (name.empty()) return "0";
  std::string clean = name;
  const std::string illegal = "<>/\\\"~:;?*=`|";
  for (char& c : clean) {
    if (illegal.find(c) != std::string::npos) {
      c = '_';
    }
  }
  size_t first = clean.find_first_not_of(" \t\r\n");
  if (first == std::string::npos) return "0";
  size_t last = clean.find_last_not_of(" \t\r\n");
  clean = clean.substr(first, last - first + 1);
  // R2000 extended symbol names (enabled by $EXTNAMES=1 in the header
  // scaffold) support up to 255 characters, but AutoCAD desktop has been
  // reported to reject long table entry names in practice - cap
  // defensively and append a short content hash on truncation so two
  // different long names sharing a common prefix don't collide.
  constexpr size_t kMaxLen = 255;
  if (clean.size() > kMaxLen) {
    std::size_t hash = std::hash<std::string>{}(clean);
    std::stringstream hs;
    hs << std::hex << (hash & 0xFFFFFFFFu);
    std::string suffix = hs.str();
    while (suffix.size() < 8) suffix = "0" + suffix;
    suffix = suffix.substr(suffix.size() - 8);
    clean = clean.substr(0, kMaxLen - suffix.size() - 1) + "_" + suffix;
  }
  return clean;
}

static int rgb_to_aci(int r, int g, int b) {
  static const std::vector<std::tuple<int, int, int, int>> standard_aci = {
      {255, 0, 0, 1},   {255, 255, 0, 2},   {0, 255, 0, 3},     {0, 255, 255, 4},  {0, 0, 255, 5},
      {255, 0, 255, 6}, {255, 255, 255, 7}, {128, 128, 128, 8}, {192, 192, 192, 9}};
  int best_aci = 7;
  double min_dist = 1e18;
  for (const auto& [sr, sg, sb, aci] : standard_aci) {
    double d = (r - sr) * (r - sr) + (g - sg) * (g - sg) + (b - sb) * (b - sb);
    if (d < min_dist) {
      min_dist = d;
      best_aci = aci;
    }
  }
  return best_aci;
}

static std::tuple<int, int, int> get_prim_rgb(const Scene& scene, const GlbPrimitive& prim) {
  int r = 200, g = 200, b = 200;
  if (prim.material_index < scene.gltf_materials.size()) {
    const auto& mat = scene.gltf_materials[prim.material_index];
    const auto& factor = mat.pbr_metallic_roughness.base_color_factor;
    r = static_cast<int>(std::round(factor[0] * 255.0));
    g = static_cast<int>(std::round(factor[1] * 255.0));
    b = static_cast<int>(std::round(factor[2] * 255.0));
  }
  return {std::max(0, std::min(255, r)), std::max(0, std::min(255, g)),
          std::max(0, std::min(255, b))};
}

// Static AutoCAD R2000 (AC1015) boilerplate, extracted byte-for-byte from a
// real ezdxf-generated file independently confirmed to open cleanly in
// desktop AutoCAD - not just lenient third-party readers. Desktop AutoCAD
// validates far more strictly than ezdxf.readfile() (or ezdxf's own
// .audit(), which also reports zero errors on incorrect output) or web
// viewers do: it needs the full CLASSES table, a real *Active VPORT
// record, and a complete OBJECTS dictionary tree (root dictionary plus
// LAYOUT records for Model/Layout1), or it silently refuses to open the
// file. Split into three header pieces so the LAYER table's per-scene
// entries can be spliced between the built-in "0"/"Defpoints" records
// (kHeaderStaticB) and the rest of TABLES/BLOCKS (kHeaderStaticC);
// kObjectsStatic needs no splicing - it carries no per-scene data at all.
// Every handle in this scaffold is a small hex literal well below 0x691,
// where dynamic (layer/entity) handles start - matching the exact starting
// handle the reference file itself uses for its own first entity, so every
// handle in an exported file stays globally unique ("monomorphic").

static const std::vector<std::string> kHeaderStaticA = [] {
  std::vector<std::string> v;
  v.push_back("  0");
  v.push_back("SECTION");
  v.push_back("  2");
  v.push_back("HEADER");
  v.push_back("  9");
  v.push_back("$ACADVER");
  v.push_back("  1");
  v.push_back("AC1015");
  v.push_back("  9");
  v.push_back("$ACADMAINTVER");
  v.push_back(" 70");
  v.push_back("6");
  v.push_back("  9");
  v.push_back("$DWGCODEPAGE");
  v.push_back("  3");
  v.push_back("ANSI_1252");
  v.push_back("  9");
  v.push_back("$INSBASE");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$EXTMIN");
  v.push_back(" 10");
  v.push_back("1e+20");
  v.push_back(" 20");
  v.push_back("1e+20");
  v.push_back(" 30");
  v.push_back("1e+20");
  v.push_back("  9");
  v.push_back("$EXTMAX");
  v.push_back(" 10");
  v.push_back("-1e+20");
  v.push_back(" 20");
  v.push_back("-1e+20");
  v.push_back(" 30");
  v.push_back("-1e+20");
  v.push_back("  9");
  v.push_back("$LIMMIN");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$LIMMAX");
  v.push_back(" 10");
  v.push_back("420.0");
  v.push_back(" 20");
  v.push_back("297.0");
  v.push_back("  9");
  v.push_back("$ORTHOMODE");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$REGENMODE");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$FILLMODE");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$QTEXTMODE");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$MIRRTEXT");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$LTSCALE");
  v.push_back(" 40");
  v.push_back("1.0");
  v.push_back("  9");
  v.push_back("$ATTMODE");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$TEXTSIZE");
  v.push_back(" 40");
  v.push_back("2.5");
  v.push_back("  9");
  v.push_back("$TRACEWID");
  v.push_back(" 40");
  v.push_back("1.0");
  v.push_back("  9");
  v.push_back("$TEXTSTYLE");
  v.push_back("  7");
  v.push_back("Standard");
  v.push_back("  9");
  v.push_back("$CLAYER");
  v.push_back("  8");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$CELTYPE");
  v.push_back("  6");
  v.push_back("ByLayer");
  v.push_back("  9");
  v.push_back("$CECOLOR");
  v.push_back(" 62");
  v.push_back("256");
  v.push_back("  9");
  v.push_back("$CELTSCALE");
  v.push_back(" 40");
  v.push_back("1.0");
  v.push_back("  9");
  v.push_back("$DISPSILH");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMSCALE");
  v.push_back(" 40");
  v.push_back("1.0");
  v.push_back("  9");
  v.push_back("$DIMASZ");
  v.push_back(" 40");
  v.push_back("2.5");
  v.push_back("  9");
  v.push_back("$DIMEXO");
  v.push_back(" 40");
  v.push_back("0.625");
  v.push_back("  9");
  v.push_back("$DIMDLI");
  v.push_back(" 40");
  v.push_back("3.75");
  v.push_back("  9");
  v.push_back("$DIMRND");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$DIMDLE");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$DIMEXE");
  v.push_back(" 40");
  v.push_back("1.25");
  v.push_back("  9");
  v.push_back("$DIMTP");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$DIMTM");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$DIMTXT");
  v.push_back(" 40");
  v.push_back("2.5");
  v.push_back("  9");
  v.push_back("$DIMCEN");
  v.push_back(" 40");
  v.push_back("2.5");
  v.push_back("  9");
  v.push_back("$DIMTSZ");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$DIMTOL");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMLIM");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMTIH");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMTOH");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMSE1");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMSE2");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMTAD");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$DIMZIN");
  v.push_back(" 70");
  v.push_back("8");
  v.push_back("  9");
  v.push_back("$DIMBLK");
  v.push_back("  1");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$DIMASO");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$DIMSHO");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$DIMPOST");
  v.push_back("  1");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$DIMAPOST");
  v.push_back("  1");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$DIMALT");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMALTD");
  v.push_back(" 70");
  v.push_back("3");
  v.push_back("  9");
  v.push_back("$DIMALTF");
  v.push_back(" 40");
  v.push_back("0.03937007874");
  v.push_back("  9");
  v.push_back("$DIMLFAC");
  v.push_back(" 40");
  v.push_back("1.0");
  v.push_back("  9");
  v.push_back("$DIMTOFL");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$DIMTVP");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$DIMTIX");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMSOXD");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMSAH");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMBLK1");
  v.push_back("  1");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$DIMBLK2");
  v.push_back("  1");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$DIMSTYLE");
  v.push_back("  2");
  v.push_back("ISO-25");
  v.push_back("  9");
  v.push_back("$DIMCLRD");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMCLRE");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMCLRT");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMTFAC");
  v.push_back(" 40");
  v.push_back("1.0");
  v.push_back("  9");
  v.push_back("$DIMGAP");
  v.push_back(" 40");
  v.push_back("0.625");
  v.push_back("  9");
  v.push_back("$DIMJUST");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMSD1");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMSD2");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMTOLJ");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMTZIN");
  v.push_back(" 70");
  v.push_back("8");
  v.push_back("  9");
  v.push_back("$DIMALTZ");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMALTTZ");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMUPT");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMDEC");
  v.push_back(" 70");
  v.push_back("2");
  v.push_back("  9");
  v.push_back("$DIMTDEC");
  v.push_back(" 70");
  v.push_back("2");
  v.push_back("  9");
  v.push_back("$DIMALTU");
  v.push_back(" 70");
  v.push_back("2");
  v.push_back("  9");
  v.push_back("$DIMALTTD");
  v.push_back(" 70");
  v.push_back("3");
  v.push_back("  9");
  v.push_back("$DIMTXSTY");
  v.push_back("  7");
  v.push_back("Standard");
  v.push_back("  9");
  v.push_back("$DIMAUNIT");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMADEC");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMALTRND");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$DIMAZIN");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMDSEP");
  v.push_back(" 70");
  v.push_back("44");
  v.push_back("  9");
  v.push_back("$DIMATFIT");
  v.push_back(" 70");
  v.push_back("3");
  v.push_back("  9");
  v.push_back("$DIMFRAC");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$DIMLDRBLK");
  v.push_back("  1");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$DIMLUNIT");
  v.push_back(" 70");
  v.push_back("2");
  v.push_back("  9");
  v.push_back("$DIMLWD");
  v.push_back(" 70");
  v.push_back("-2");
  v.push_back("  9");
  v.push_back("$DIMLWE");
  v.push_back(" 70");
  v.push_back("-2");
  v.push_back("  9");
  v.push_back("$DIMTMOVE");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$LUNITS");
  v.push_back(" 70");
  v.push_back("2");
  v.push_back("  9");
  v.push_back("$LUPREC");
  v.push_back(" 70");
  v.push_back("4");
  v.push_back("  9");
  v.push_back("$SKETCHINC");
  v.push_back(" 40");
  v.push_back("1.0");
  v.push_back("  9");
  v.push_back("$FILLETRAD");
  v.push_back(" 40");
  v.push_back("10.0");
  v.push_back("  9");
  v.push_back("$AUNITS");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$AUPREC");
  v.push_back(" 70");
  v.push_back("2");
  v.push_back("  9");
  v.push_back("$MENU");
  v.push_back("  1");
  v.push_back(".");
  v.push_back("  9");
  v.push_back("$ELEVATION");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PELEVATION");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$THICKNESS");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$LIMCHECK");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$CHAMFERA");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$CHAMFERB");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$CHAMFERC");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$CHAMFERD");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$SKPOLY");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$TDCREATE");
  v.push_back(" 40");
  v.push_back("2461265.626689815");
  v.push_back("  9");
  v.push_back("$TDUCREATE");
  v.push_back(" 40");
  v.push_back("2458532.153996898");
  v.push_back("  9");
  v.push_back("$TDUPDATE");
  v.push_back(" 40");
  v.push_back("2461265.626689815");
  v.push_back("  9");
  v.push_back("$TDUUPDATE");
  v.push_back(" 40");
  v.push_back("2458532.1544311");
  v.push_back("  9");
  v.push_back("$TDINDWG");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$TDUSRTIMER");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$USRTIMER");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$ANGBASE");
  v.push_back(" 50");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$ANGDIR");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$PDMODE");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$PDSIZE");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PLINEWID");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$SPLFRAME");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$SPLINETYPE");
  v.push_back(" 70");
  v.push_back("6");
  v.push_back("  9");
  v.push_back("$SPLINESEGS");
  v.push_back(" 70");
  v.push_back("8");
  v.push_back("  9");
  v.push_back("$HANDSEED");
  v.push_back("  5");
  v.push_back("__HANDSEED__");
  v.push_back("  9");
  v.push_back("$SURFTAB1");
  v.push_back(" 70");
  v.push_back("6");
  v.push_back("  9");
  v.push_back("$SURFTAB2");
  v.push_back(" 70");
  v.push_back("6");
  v.push_back("  9");
  v.push_back("$SURFTYPE");
  v.push_back(" 70");
  v.push_back("6");
  v.push_back("  9");
  v.push_back("$SURFU");
  v.push_back(" 70");
  v.push_back("6");
  v.push_back("  9");
  v.push_back("$SURFV");
  v.push_back(" 70");
  v.push_back("6");
  v.push_back("  9");
  v.push_back("$UCSBASE");
  v.push_back("  2");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$UCSNAME");
  v.push_back("  2");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$UCSORG");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$UCSXDIR");
  v.push_back(" 10");
  v.push_back("1.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$UCSYDIR");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("1.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$UCSORTHOREF");
  v.push_back("  2");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$UCSORTHOVIEW");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$UCSORGTOP");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$UCSORGBOTTOM");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$UCSORGLEFT");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$UCSORGRIGHT");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$UCSORGFRONT");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$UCSORGBACK");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PUCSBASE");
  v.push_back("  2");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$PUCSNAME");
  v.push_back("  2");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$PUCSORG");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PUCSXDIR");
  v.push_back(" 10");
  v.push_back("1.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PUCSYDIR");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("1.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PUCSORTHOREF");
  v.push_back("  2");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$PUCSORTHOVIEW");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$PUCSORGTOP");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PUCSORGBOTTOM");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PUCSORGLEFT");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PUCSORGRIGHT");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PUCSORGFRONT");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PUCSORGBACK");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$USERI1");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$USERI2");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$USERI3");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$USERI4");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$USERI5");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$USERR1");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$USERR2");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$USERR3");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$USERR4");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$USERR5");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$WORLDVIEW");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$SHADEDGE");
  v.push_back(" 70");
  v.push_back("3");
  v.push_back("  9");
  v.push_back("$SHADEDIF");
  v.push_back(" 70");
  v.push_back("70");
  v.push_back("  9");
  v.push_back("$TILEMODE");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$MAXACTVP");
  v.push_back(" 70");
  v.push_back("64");
  v.push_back("  9");
  v.push_back("$PINSBASE");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PLIMCHECK");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$PEXTMIN");
  v.push_back(" 10");
  v.push_back("1e+20");
  v.push_back(" 20");
  v.push_back("1e+20");
  v.push_back(" 30");
  v.push_back("1e+20");
  v.push_back("  9");
  v.push_back("$PEXTMAX");
  v.push_back(" 10");
  v.push_back("-1e+20");
  v.push_back(" 20");
  v.push_back("-1e+20");
  v.push_back(" 30");
  v.push_back("-1e+20");
  v.push_back("  9");
  v.push_back("$PLIMMIN");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$PLIMMAX");
  v.push_back(" 10");
  v.push_back("420.0");
  v.push_back(" 20");
  v.push_back("297.0");
  v.push_back("  9");
  v.push_back("$UNITMODE");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$VISRETAIN");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$PLINEGEN");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$PSLTSCALE");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$TREEDEPTH");
  v.push_back(" 70");
  v.push_back("3020");
  v.push_back("  9");
  v.push_back("$CMLSTYLE");
  v.push_back("  2");
  v.push_back("Standard");
  v.push_back("  9");
  v.push_back("$CMLJUST");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$CMLSCALE");
  v.push_back(" 40");
  v.push_back("20.0");
  v.push_back("  9");
  v.push_back("$PROXYGRAPHICS");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$MEASUREMENT");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$CELWEIGHT");
  v.push_back("370");
  v.push_back("-1");
  v.push_back("  9");
  v.push_back("$ENDCAPS");
  v.push_back("280");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$JOINSTYLE");
  v.push_back("280");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$LWDISPLAY");
  v.push_back("290");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$INSUNITS");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$HYPERLINKBASE");
  v.push_back("  1");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$STYLESHEET");
  v.push_back("  1");
  v.push_back("");
  v.push_back("  9");
  v.push_back("$XEDIT");
  v.push_back("290");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$CEPSNTYPE");
  v.push_back("380");
  v.push_back("0");
  v.push_back("  9");
  v.push_back("$PSTYLEMODE");
  v.push_back("290");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$FINGERPRINTGUID");
  v.push_back("  2");
  v.push_back("{901E6446-C8CA-4381-B5FE-8494D931A798}");
  v.push_back("  9");
  v.push_back("$VERSIONGUID");
  v.push_back("  2");
  v.push_back("{4B5A3BC4-57FB-4960-955B-D909E47DC28A}");
  v.push_back("  9");
  v.push_back("$EXTNAMES");
  v.push_back("290");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("$PSVPSCALE");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  9");
  v.push_back("$OLESTARTUP");
  v.push_back("290");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("ENDSEC");
  v.push_back("  0");
  v.push_back("SECTION");
  v.push_back("  2");
  v.push_back("CLASSES");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("ACDBDICTIONARYWDFLT");
  v.push_back("  2");
  v.push_back("AcDbDictionaryWithDefault");
  v.push_back("  3");
  v.push_back("ObjectDBX Classes");
  v.push_back(" 90");
  v.push_back("0");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("SUN");
  v.push_back("  2");
  v.push_back("AcDbSun");
  v.push_back("  3");
  v.push_back("SCENEOE");
  v.push_back(" 90");
  v.push_back("1153");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("VISUALSTYLE");
  v.push_back("  2");
  v.push_back("AcDbVisualStyle");
  v.push_back("  3");
  v.push_back("ObjectDBX Classes");
  v.push_back(" 90");
  v.push_back("4095");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("MATERIAL");
  v.push_back("  2");
  v.push_back("AcDbMaterial");
  v.push_back("  3");
  v.push_back("ObjectDBX Classes");
  v.push_back(" 90");
  v.push_back("1153");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("SCALE");
  v.push_back("  2");
  v.push_back("AcDbScale");
  v.push_back("  3");
  v.push_back("ObjectDBX Classes");
  v.push_back(" 90");
  v.push_back("1153");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("TABLESTYLE");
  v.push_back("  2");
  v.push_back("AcDbTableStyle");
  v.push_back("  3");
  v.push_back("ObjectDBX Classes");
  v.push_back(" 90");
  v.push_back("4095");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("MLEADERSTYLE");
  v.push_back("  2");
  v.push_back("AcDbMLeaderStyle");
  v.push_back("  3");
  v.push_back("ACDB_MLEADERSTYLE_CLASS");
  v.push_back(" 90");
  v.push_back("4095");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("DICTIONARYVAR");
  v.push_back("  2");
  v.push_back("AcDbDictionaryVar");
  v.push_back("  3");
  v.push_back("ObjectDBX Classes");
  v.push_back(" 90");
  v.push_back("0");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("CELLSTYLEMAP");
  v.push_back("  2");
  v.push_back("AcDbCellStyleMap");
  v.push_back("  3");
  v.push_back("ObjectDBX Classes");
  v.push_back(" 90");
  v.push_back("1152");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("MENTALRAYRENDERSETTINGS");
  v.push_back("  2");
  v.push_back("AcDbMentalRayRenderSettings");
  v.push_back("  3");
  v.push_back("SCENEOE");
  v.push_back(" 90");
  v.push_back("1024");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("ACDBDETAILVIEWSTYLE");
  v.push_back("  2");
  v.push_back("AcDbDetailViewStyle");
  v.push_back("  3");
  v.push_back("ObjectDBX Classes");
  v.push_back(" 90");
  v.push_back("1025");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("ACDBSECTIONVIEWSTYLE");
  v.push_back("  2");
  v.push_back("AcDbSectionViewStyle");
  v.push_back("  3");
  v.push_back("ObjectDBX Classes");
  v.push_back(" 90");
  v.push_back("1025");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("RASTERVARIABLES");
  v.push_back("  2");
  v.push_back("AcDbRasterVariables");
  v.push_back("  3");
  v.push_back("ISM");
  v.push_back(" 90");
  v.push_back("0");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("ACDBPLACEHOLDER");
  v.push_back("  2");
  v.push_back("AcDbPlaceHolder");
  v.push_back("  3");
  v.push_back("ObjectDBX Classes");
  v.push_back(" 90");
  v.push_back("0");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("CLASS");
  v.push_back("  1");
  v.push_back("LAYOUT");
  v.push_back("  2");
  v.push_back("AcDbLayout");
  v.push_back("  3");
  v.push_back("ObjectDBX Classes");
  v.push_back(" 90");
  v.push_back("0");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("ENDSEC");
  v.push_back("  0");
  v.push_back("SECTION");
  v.push_back("  2");
  v.push_back("TABLES");
  v.push_back("  0");
  v.push_back("TABLE");
  v.push_back("  2");
  v.push_back("VPORT");
  v.push_back("  5");
  v.push_back("8");
  v.push_back("330");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbSymbolTable");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  0");
  v.push_back("VPORT");
  v.push_back("  5");
  v.push_back("23");
  v.push_back("330");
  v.push_back("8");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbViewportTableRecord");
  v.push_back("  2");
  v.push_back("*Active");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 11");
  v.push_back("1.0");
  v.push_back(" 21");
  v.push_back("1.0");
  v.push_back(" 12");
  v.push_back("0.0");
  v.push_back(" 22");
  v.push_back("0.0");
  v.push_back(" 13");
  v.push_back("0.0");
  v.push_back(" 23");
  v.push_back("0.0");
  v.push_back(" 14");
  v.push_back("0.5");
  v.push_back(" 24");
  v.push_back("0.5");
  v.push_back(" 15");
  v.push_back("0.5");
  v.push_back(" 25");
  v.push_back("0.5");
  v.push_back(" 16");
  v.push_back("0.0");
  v.push_back(" 26");
  v.push_back("0.0");
  v.push_back(" 36");
  v.push_back("1.0");
  v.push_back(" 17");
  v.push_back("0.0");
  v.push_back(" 27");
  v.push_back("0.0");
  v.push_back(" 37");
  v.push_back("0.0");
  v.push_back(" 40");
  v.push_back("1000.0");
  v.push_back(" 41");
  v.push_back("1.34");
  v.push_back(" 42");
  v.push_back("50.0");
  v.push_back(" 43");
  v.push_back("0.0");
  v.push_back(" 44");
  v.push_back("0.0");
  v.push_back(" 50");
  v.push_back("0.0");
  v.push_back(" 51");
  v.push_back("0.0");
  v.push_back(" 71");
  v.push_back("0");
  v.push_back(" 72");
  v.push_back("1000");
  v.push_back(" 73");
  v.push_back("1");
  v.push_back(" 74");
  v.push_back("3");
  v.push_back(" 75");
  v.push_back("0");
  v.push_back(" 76");
  v.push_back("0");
  v.push_back(" 77");
  v.push_back("0");
  v.push_back(" 78");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back(" 65");
  v.push_back("0");
  v.push_back("146");
  v.push_back("0.0");
  v.push_back("  0");
  v.push_back("ENDTAB");
  v.push_back("  0");
  v.push_back("TABLE");
  v.push_back("  2");
  v.push_back("LTYPE");
  v.push_back("  5");
  v.push_back("2");
  v.push_back("330");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbSymbolTable");
  v.push_back(" 70");
  v.push_back("3");
  v.push_back("  0");
  v.push_back("LTYPE");
  v.push_back("  5");
  v.push_back("24");
  v.push_back("330");
  v.push_back("2");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbLinetypeTableRecord");
  v.push_back("  2");
  v.push_back("ByBlock");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  3");
  v.push_back("");
  v.push_back(" 72");
  v.push_back("65");
  v.push_back(" 73");
  v.push_back("0");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  0");
  v.push_back("LTYPE");
  v.push_back("  5");
  v.push_back("25");
  v.push_back("330");
  v.push_back("2");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbLinetypeTableRecord");
  v.push_back("  2");
  v.push_back("ByLayer");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  3");
  v.push_back("");
  v.push_back(" 72");
  v.push_back("65");
  v.push_back(" 73");
  v.push_back("0");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  0");
  v.push_back("LTYPE");
  v.push_back("  5");
  v.push_back("26");
  v.push_back("330");
  v.push_back("2");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbLinetypeTableRecord");
  v.push_back("  2");
  v.push_back("Continuous");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  3");
  v.push_back("");
  v.push_back(" 72");
  v.push_back("65");
  v.push_back(" 73");
  v.push_back("0");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back("  0");
  v.push_back("ENDTAB");
  v.push_back("  0");
  v.push_back("TABLE");
  v.push_back("  2");
  v.push_back("LAYER");
  v.push_back("  5");
  v.push_back("1");
  v.push_back("330");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbSymbolTable");
  v.push_back(" 70");
  return v;
}();

static const std::vector<std::string> kHeaderStaticB = [] {
  std::vector<std::string> v;
  v.push_back("  0");
  v.push_back("LAYER");
  v.push_back("  5");
  v.push_back("27");
  v.push_back("330");
  v.push_back("1");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbLayerTableRecord");
  v.push_back("  2");
  v.push_back("0");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back(" 62");
  v.push_back("7");
  v.push_back("  6");
  v.push_back("Continuous");
  v.push_back("370");
  v.push_back("-3");
  v.push_back("390");
  v.push_back("13");
  v.push_back("  0");
  v.push_back("LAYER");
  v.push_back("  5");
  v.push_back("28");
  v.push_back("330");
  v.push_back("1");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbLayerTableRecord");
  v.push_back("  2");
  v.push_back("Defpoints");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back(" 62");
  v.push_back("7");
  v.push_back("  6");
  v.push_back("Continuous");
  v.push_back("290");
  v.push_back("0");
  v.push_back("370");
  v.push_back("-3");
  v.push_back("390");
  v.push_back("13");
  return v;
}();

static const std::vector<std::string> kHeaderStaticC = [] {
  std::vector<std::string> v;
  v.push_back("  0");
  v.push_back("ENDTAB");
  v.push_back("  0");
  v.push_back("TABLE");
  v.push_back("  2");
  v.push_back("STYLE");
  v.push_back("  5");
  v.push_back("5");
  v.push_back("330");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbSymbolTable");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("  0");
  v.push_back("STYLE");
  v.push_back("  5");
  v.push_back("29");
  v.push_back("330");
  v.push_back("5");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbTextStyleTableRecord");
  v.push_back("  2");
  v.push_back("Standard");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back(" 41");
  v.push_back("1.0");
  v.push_back(" 50");
  v.push_back("0.0");
  v.push_back(" 71");
  v.push_back("0");
  v.push_back(" 42");
  v.push_back("2.5");
  v.push_back("  3");
  v.push_back("txt");
  v.push_back("  4");
  v.push_back("");
  v.push_back("  0");
  v.push_back("ENDTAB");
  v.push_back("  0");
  v.push_back("TABLE");
  v.push_back("  2");
  v.push_back("VIEW");
  v.push_back("  5");
  v.push_back("7");
  v.push_back("330");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbSymbolTable");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("ENDTAB");
  v.push_back("  0");
  v.push_back("TABLE");
  v.push_back("  2");
  v.push_back("UCS");
  v.push_back("  5");
  v.push_back("6");
  v.push_back("330");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbSymbolTable");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("ENDTAB");
  v.push_back("  0");
  v.push_back("TABLE");
  v.push_back("  2");
  v.push_back("APPID");
  v.push_back("  5");
  v.push_back("3");
  v.push_back("330");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbSymbolTable");
  v.push_back(" 70");
  v.push_back("3");
  v.push_back("  0");
  v.push_back("APPID");
  v.push_back("  5");
  v.push_back("2A");
  v.push_back("330");
  v.push_back("3");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbRegAppTableRecord");
  v.push_back("  2");
  v.push_back("ACAD");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("APPID");
  v.push_back("  5");
  v.push_back("2F");
  v.push_back("330");
  v.push_back("3");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbRegAppTableRecord");
  v.push_back("  2");
  v.push_back("HATCHBACKGROUNDCOLOR");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("APPID");
  v.push_back("  5");
  v.push_back("30");
  v.push_back("330");
  v.push_back("3");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbRegAppTableRecord");
  v.push_back("  2");
  v.push_back("EZDXF");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  0");
  v.push_back("ENDTAB");
  v.push_back("  0");
  v.push_back("TABLE");
  v.push_back("  2");
  v.push_back("DIMSTYLE");
  v.push_back("  5");
  v.push_back("4");
  v.push_back("330");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbSymbolTable");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back("100");
  v.push_back("AcDbDimStyleTable");
  v.push_back("  0");
  v.push_back("DIMSTYLE");
  v.push_back("105");
  v.push_back("2B");
  v.push_back("330");
  v.push_back("4");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbDimStyleTableRecord");
  v.push_back("  2");
  v.push_back("Standard");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  3");
  v.push_back("");
  v.push_back("  4");
  v.push_back("");
  v.push_back(" 40");
  v.push_back("1.0");
  v.push_back(" 41");
  v.push_back("2.5");
  v.push_back(" 42");
  v.push_back("0.625");
  v.push_back(" 43");
  v.push_back("3.75");
  v.push_back(" 44");
  v.push_back("1.25");
  v.push_back(" 45");
  v.push_back("0.0");
  v.push_back(" 46");
  v.push_back("0.0");
  v.push_back(" 47");
  v.push_back("0.0");
  v.push_back(" 48");
  v.push_back("0.0");
  v.push_back("140");
  v.push_back("2.5");
  v.push_back("141");
  v.push_back("2.5");
  v.push_back("142");
  v.push_back("0.0");
  v.push_back("143");
  v.push_back("0.03937007874");
  v.push_back("144");
  v.push_back("1.0");
  v.push_back("145");
  v.push_back("0.0");
  v.push_back("146");
  v.push_back("1.0");
  v.push_back("147");
  v.push_back("0.625");
  v.push_back("148");
  v.push_back("0.0");
  v.push_back(" 71");
  v.push_back("0");
  v.push_back(" 72");
  v.push_back("0");
  v.push_back(" 73");
  v.push_back("0");
  v.push_back(" 74");
  v.push_back("0");
  v.push_back(" 75");
  v.push_back("0");
  v.push_back(" 76");
  v.push_back("0");
  v.push_back(" 77");
  v.push_back("1");
  v.push_back(" 78");
  v.push_back("8");
  v.push_back(" 79");
  v.push_back("3");
  v.push_back("170");
  v.push_back("0");
  v.push_back("171");
  v.push_back("3");
  v.push_back("172");
  v.push_back("1");
  v.push_back("173");
  v.push_back("0");
  v.push_back("174");
  v.push_back("0");
  v.push_back("175");
  v.push_back("0");
  v.push_back("176");
  v.push_back("0");
  v.push_back("177");
  v.push_back("0");
  v.push_back("178");
  v.push_back("0");
  v.push_back("179");
  v.push_back("2");
  v.push_back("271");
  v.push_back("2");
  v.push_back("272");
  v.push_back("2");
  v.push_back("273");
  v.push_back("2");
  v.push_back("274");
  v.push_back("3");
  v.push_back("275");
  v.push_back("0");
  v.push_back("276");
  v.push_back("0");
  v.push_back("277");
  v.push_back("2");
  v.push_back("278");
  v.push_back("44");
  v.push_back("279");
  v.push_back("0");
  v.push_back("280");
  v.push_back("0");
  v.push_back("281");
  v.push_back("0");
  v.push_back("282");
  v.push_back("0");
  v.push_back("283");
  v.push_back("0");
  v.push_back("284");
  v.push_back("8");
  v.push_back("285");
  v.push_back("0");
  v.push_back("286");
  v.push_back("0");
  v.push_back("288");
  v.push_back("0");
  v.push_back("289");
  v.push_back("3");
  v.push_back("371");
  v.push_back("-2");
  v.push_back("372");
  v.push_back("-2");
  v.push_back("  0");
  v.push_back("ENDTAB");
  v.push_back("  0");
  v.push_back("TABLE");
  v.push_back("  2");
  v.push_back("BLOCK_RECORD");
  v.push_back("  5");
  v.push_back("9");
  v.push_back("330");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbSymbolTable");
  v.push_back(" 70");
  v.push_back("2");
  v.push_back("  0");
  v.push_back("BLOCK_RECORD");
  v.push_back("  5");
  v.push_back("17");
  v.push_back("330");
  v.push_back("9");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbBlockTableRecord");
  v.push_back("  2");
  v.push_back("*Model_Space");
  v.push_back("340");
  v.push_back("1A");
  v.push_back("  0");
  v.push_back("BLOCK_RECORD");
  v.push_back("  5");
  v.push_back("1B");
  v.push_back("330");
  v.push_back("9");
  v.push_back("100");
  v.push_back("AcDbSymbolTableRecord");
  v.push_back("100");
  v.push_back("AcDbBlockTableRecord");
  v.push_back("  2");
  v.push_back("*Paper_Space");
  v.push_back("340");
  v.push_back("1E");
  v.push_back("  0");
  v.push_back("ENDTAB");
  v.push_back("  0");
  v.push_back("ENDSEC");
  v.push_back("  0");
  v.push_back("SECTION");
  v.push_back("  2");
  v.push_back("BLOCKS");
  v.push_back("  0");
  v.push_back("BLOCK");
  v.push_back("  5");
  v.push_back("18");
  v.push_back("330");
  v.push_back("17");
  v.push_back("100");
  v.push_back("AcDbEntity");
  v.push_back("  8");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbBlockBegin");
  v.push_back("  2");
  v.push_back("*Model_Space");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  3");
  v.push_back("*Model_Space");
  v.push_back("  1");
  v.push_back("");
  v.push_back("  0");
  v.push_back("ENDBLK");
  v.push_back("  5");
  v.push_back("19");
  v.push_back("330");
  v.push_back("17");
  v.push_back("100");
  v.push_back("AcDbEntity");
  v.push_back("  8");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbBlockEnd");
  v.push_back("  0");
  v.push_back("BLOCK");
  v.push_back("  5");
  v.push_back("1C");
  v.push_back("330");
  v.push_back("1B");
  v.push_back("100");
  v.push_back("AcDbEntity");
  v.push_back("  8");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbBlockBegin");
  v.push_back("  2");
  v.push_back("*Paper_Space");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 30");
  v.push_back("0.0");
  v.push_back("  3");
  v.push_back("*Paper_Space");
  v.push_back("  1");
  v.push_back("");
  v.push_back("  0");
  v.push_back("ENDBLK");
  v.push_back("  5");
  v.push_back("1D");
  v.push_back("330");
  v.push_back("1B");
  v.push_back("100");
  v.push_back("AcDbEntity");
  v.push_back("  8");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbBlockEnd");
  v.push_back("  0");
  v.push_back("ENDSEC");
  return v;
}();

static const std::vector<std::string> kObjectsStatic = [] {
  std::vector<std::string> v;
  v.push_back("  0");
  v.push_back("SECTION");
  v.push_back("  2");
  v.push_back("OBJECTS");
  v.push_back("  0");
  v.push_back("DICTIONARY");
  v.push_back("  5");
  v.push_back("A");
  v.push_back("330");
  v.push_back("0");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("ACAD_COLOR");
  v.push_back("350");
  v.push_back("B");
  v.push_back("  3");
  v.push_back("ACAD_GROUP");
  v.push_back("350");
  v.push_back("C");
  v.push_back("  3");
  v.push_back("ACAD_LAYOUT");
  v.push_back("350");
  v.push_back("D");
  v.push_back("  3");
  v.push_back("ACAD_MATERIAL");
  v.push_back("350");
  v.push_back("E");
  v.push_back("  3");
  v.push_back("ACAD_MLEADERSTYLE");
  v.push_back("350");
  v.push_back("F");
  v.push_back("  3");
  v.push_back("ACAD_MLINESTYLE");
  v.push_back("350");
  v.push_back("10");
  v.push_back("  3");
  v.push_back("ACAD_PLOTSETTINGS");
  v.push_back("350");
  v.push_back("11");
  v.push_back("  3");
  v.push_back("ACAD_PLOTSTYLENAME");
  v.push_back("350");
  v.push_back("12");
  v.push_back("  3");
  v.push_back("ACAD_SCALELIST");
  v.push_back("350");
  v.push_back("14");
  v.push_back("  3");
  v.push_back("ACAD_TABLESTYLE");
  v.push_back("350");
  v.push_back("15");
  v.push_back("  3");
  v.push_back("ACAD_VISUALSTYLE");
  v.push_back("350");
  v.push_back("16");
  v.push_back("  3");
  v.push_back("EZDXF_META");
  v.push_back("350");
  v.push_back("2D");
  v.push_back("  0");
  v.push_back("DICTIONARY");
  v.push_back("  5");
  v.push_back("B");
  v.push_back("330");
  v.push_back("A");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  0");
  v.push_back("DICTIONARY");
  v.push_back("  5");
  v.push_back("C");
  v.push_back("330");
  v.push_back("A");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  0");
  v.push_back("DICTIONARY");
  v.push_back("  5");
  v.push_back("D");
  v.push_back("330");
  v.push_back("A");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("Model");
  v.push_back("350");
  v.push_back("1A");
  v.push_back("  3");
  v.push_back("Layout1");
  v.push_back("350");
  v.push_back("1E");
  v.push_back("  0");
  v.push_back("DICTIONARY");
  v.push_back("  5");
  v.push_back("E");
  v.push_back("330");
  v.push_back("A");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("ByBlock");
  v.push_back("350");
  v.push_back("1F");
  v.push_back("  3");
  v.push_back("ByLayer");
  v.push_back("350");
  v.push_back("20");
  v.push_back("  3");
  v.push_back("Global");
  v.push_back("350");
  v.push_back("21");
  v.push_back("  0");
  v.push_back("DICTIONARY");
  v.push_back("  5");
  v.push_back("F");
  v.push_back("330");
  v.push_back("A");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("Standard");
  v.push_back("350");
  v.push_back("2C");
  v.push_back("  0");
  v.push_back("DICTIONARY");
  v.push_back("  5");
  v.push_back("10");
  v.push_back("330");
  v.push_back("A");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("Standard");
  v.push_back("350");
  v.push_back("22");
  v.push_back("  0");
  v.push_back("DICTIONARY");
  v.push_back("  5");
  v.push_back("11");
  v.push_back("330");
  v.push_back("A");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  0");
  v.push_back("ACDBDICTIONARYWDFLT");
  v.push_back("  5");
  v.push_back("12");
  v.push_back("330");
  v.push_back("A");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("Normal");
  v.push_back("350");
  v.push_back("13");
  v.push_back("100");
  v.push_back("AcDbDictionaryWithDefault");
  v.push_back("340");
  v.push_back("13");
  v.push_back("  0");
  v.push_back("ACDBPLACEHOLDER");
  v.push_back("  5");
  v.push_back("13");
  v.push_back("330");
  v.push_back("12");
  v.push_back("  0");
  v.push_back("DICTIONARY");
  v.push_back("  5");
  v.push_back("14");
  v.push_back("330");
  v.push_back("A");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  0");
  v.push_back("DICTIONARY");
  v.push_back("  5");
  v.push_back("15");
  v.push_back("330");
  v.push_back("A");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  0");
  v.push_back("DICTIONARY");
  v.push_back("  5");
  v.push_back("16");
  v.push_back("330");
  v.push_back("A");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  0");
  v.push_back("LAYOUT");
  v.push_back("  5");
  v.push_back("1A");
  v.push_back("330");
  v.push_back("D");
  v.push_back("100");
  v.push_back("AcDbPlotSettings");
  v.push_back("  1");
  v.push_back("");
  v.push_back("  4");
  v.push_back("A3");
  v.push_back("  6");
  v.push_back("");
  v.push_back(" 40");
  v.push_back("7.5");
  v.push_back(" 41");
  v.push_back("20.0");
  v.push_back(" 42");
  v.push_back("7.5");
  v.push_back(" 43");
  v.push_back("20.0");
  v.push_back(" 44");
  v.push_back("420.0");
  v.push_back(" 45");
  v.push_back("297.0");
  v.push_back(" 46");
  v.push_back("0.0");
  v.push_back(" 47");
  v.push_back("0.0");
  v.push_back(" 48");
  v.push_back("0.0");
  v.push_back(" 49");
  v.push_back("0.0");
  v.push_back("140");
  v.push_back("0.0");
  v.push_back("141");
  v.push_back("0.0");
  v.push_back("142");
  v.push_back("1.0");
  v.push_back("143");
  v.push_back("1.0");
  v.push_back(" 70");
  v.push_back("1024");
  v.push_back(" 72");
  v.push_back("1");
  v.push_back(" 73");
  v.push_back("0");
  v.push_back(" 74");
  v.push_back("5");
  v.push_back("  7");
  v.push_back("");
  v.push_back(" 75");
  v.push_back("16");
  v.push_back(" 76");
  v.push_back("0");
  v.push_back(" 77");
  v.push_back("2");
  v.push_back(" 78");
  v.push_back("300");
  v.push_back("147");
  v.push_back("1.0");
  v.push_back("148");
  v.push_back("0.0");
  v.push_back("149");
  v.push_back("0.0");
  v.push_back("100");
  v.push_back("AcDbLayout");
  v.push_back("  1");
  v.push_back("Model");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back(" 71");
  v.push_back("0");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 11");
  v.push_back("420.0");
  v.push_back(" 21");
  v.push_back("297.0");
  v.push_back(" 12");
  v.push_back("0.0");
  v.push_back(" 22");
  v.push_back("0.0");
  v.push_back(" 32");
  v.push_back("0.0");
  v.push_back(" 14");
  v.push_back("1e+20");
  v.push_back(" 24");
  v.push_back("1e+20");
  v.push_back(" 34");
  v.push_back("1e+20");
  v.push_back(" 15");
  v.push_back("-1e+20");
  v.push_back(" 25");
  v.push_back("-1e+20");
  v.push_back(" 35");
  v.push_back("-1e+20");
  v.push_back("146");
  v.push_back("0.0");
  v.push_back(" 13");
  v.push_back("0.0");
  v.push_back(" 23");
  v.push_back("0.0");
  v.push_back(" 33");
  v.push_back("0.0");
  v.push_back(" 16");
  v.push_back("1.0");
  v.push_back(" 26");
  v.push_back("0.0");
  v.push_back(" 36");
  v.push_back("0.0");
  v.push_back(" 17");
  v.push_back("0.0");
  v.push_back(" 27");
  v.push_back("1.0");
  v.push_back(" 37");
  v.push_back("0.0");
  v.push_back(" 76");
  v.push_back("1");
  v.push_back("330");
  v.push_back("17");
  v.push_back("  0");
  v.push_back("LAYOUT");
  v.push_back("  5");
  v.push_back("1E");
  v.push_back("330");
  v.push_back("D");
  v.push_back("100");
  v.push_back("AcDbPlotSettings");
  v.push_back("  1");
  v.push_back("");
  v.push_back("  4");
  v.push_back("A3");
  v.push_back("  6");
  v.push_back("");
  v.push_back(" 40");
  v.push_back("7.5");
  v.push_back(" 41");
  v.push_back("20.0");
  v.push_back(" 42");
  v.push_back("7.5");
  v.push_back(" 43");
  v.push_back("20.0");
  v.push_back(" 44");
  v.push_back("420.0");
  v.push_back(" 45");
  v.push_back("297.0");
  v.push_back(" 46");
  v.push_back("0.0");
  v.push_back(" 47");
  v.push_back("0.0");
  v.push_back(" 48");
  v.push_back("0.0");
  v.push_back(" 49");
  v.push_back("0.0");
  v.push_back("140");
  v.push_back("0.0");
  v.push_back("141");
  v.push_back("0.0");
  v.push_back("142");
  v.push_back("1.0");
  v.push_back("143");
  v.push_back("1.0");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back(" 72");
  v.push_back("1");
  v.push_back(" 73");
  v.push_back("0");
  v.push_back(" 74");
  v.push_back("5");
  v.push_back("  7");
  v.push_back("");
  v.push_back(" 75");
  v.push_back("16");
  v.push_back(" 76");
  v.push_back("0");
  v.push_back(" 77");
  v.push_back("2");
  v.push_back(" 78");
  v.push_back("300");
  v.push_back("147");
  v.push_back("1.0");
  v.push_back("148");
  v.push_back("0.0");
  v.push_back("149");
  v.push_back("0.0");
  v.push_back("100");
  v.push_back("AcDbLayout");
  v.push_back("  1");
  v.push_back("Layout1");
  v.push_back(" 70");
  v.push_back("1");
  v.push_back(" 71");
  v.push_back("1");
  v.push_back(" 10");
  v.push_back("0.0");
  v.push_back(" 20");
  v.push_back("0.0");
  v.push_back(" 11");
  v.push_back("420.0");
  v.push_back(" 21");
  v.push_back("297.0");
  v.push_back(" 12");
  v.push_back("0.0");
  v.push_back(" 22");
  v.push_back("0.0");
  v.push_back(" 32");
  v.push_back("0.0");
  v.push_back(" 14");
  v.push_back("1e+20");
  v.push_back(" 24");
  v.push_back("1e+20");
  v.push_back(" 34");
  v.push_back("1e+20");
  v.push_back(" 15");
  v.push_back("-1e+20");
  v.push_back(" 25");
  v.push_back("-1e+20");
  v.push_back(" 35");
  v.push_back("-1e+20");
  v.push_back("146");
  v.push_back("0.0");
  v.push_back(" 13");
  v.push_back("0.0");
  v.push_back(" 23");
  v.push_back("0.0");
  v.push_back(" 33");
  v.push_back("0.0");
  v.push_back(" 16");
  v.push_back("1.0");
  v.push_back(" 26");
  v.push_back("0.0");
  v.push_back(" 36");
  v.push_back("0.0");
  v.push_back(" 17");
  v.push_back("0.0");
  v.push_back(" 27");
  v.push_back("1.0");
  v.push_back(" 37");
  v.push_back("0.0");
  v.push_back(" 76");
  v.push_back("1");
  v.push_back("330");
  v.push_back("1B");
  v.push_back("  0");
  v.push_back("MATERIAL");
  v.push_back("  5");
  v.push_back("1F");
  v.push_back("102");
  v.push_back("{ACAD_REACTORS");
  v.push_back("330");
  v.push_back("E");
  v.push_back("102");
  v.push_back("}");
  v.push_back("330");
  v.push_back("E");
  v.push_back("100");
  v.push_back("AcDbMaterial");
  v.push_back("  1");
  v.push_back("ByBlock");
  v.push_back("  2");
  v.push_back("");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back(" 40");
  v.push_back("1.0");
  v.push_back(" 71");
  v.push_back("1");
  v.push_back(" 41");
  v.push_back("1.0");
  v.push_back(" 91");
  v.push_back("-1023410177");
  v.push_back(" 42");
  v.push_back("1.0");
  v.push_back(" 72");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("");
  v.push_back(" 73");
  v.push_back("1");
  v.push_back(" 74");
  v.push_back("1");
  v.push_back(" 75");
  v.push_back("1");
  v.push_back(" 44");
  v.push_back("0.5");
  v.push_back(" 73");
  v.push_back("0");
  v.push_back(" 45");
  v.push_back("1.0");
  v.push_back(" 46");
  v.push_back("1.0");
  v.push_back(" 77");
  v.push_back("1");
  v.push_back("  4");
  v.push_back("");
  v.push_back(" 78");
  v.push_back("1");
  v.push_back(" 79");
  v.push_back("1");
  v.push_back("170");
  v.push_back("1");
  v.push_back(" 48");
  v.push_back("1.0");
  v.push_back("171");
  v.push_back("1");
  v.push_back("  6");
  v.push_back("");
  v.push_back("172");
  v.push_back("1");
  v.push_back("173");
  v.push_back("1");
  v.push_back("174");
  v.push_back("1");
  v.push_back("140");
  v.push_back("1.0");
  v.push_back("141");
  v.push_back("1.0");
  v.push_back("175");
  v.push_back("1");
  v.push_back("  7");
  v.push_back("");
  v.push_back("176");
  v.push_back("1");
  v.push_back("177");
  v.push_back("1");
  v.push_back("178");
  v.push_back("1");
  v.push_back("143");
  v.push_back("1.0");
  v.push_back("179");
  v.push_back("1");
  v.push_back("  8");
  v.push_back("");
  v.push_back("270");
  v.push_back("1");
  v.push_back("271");
  v.push_back("1");
  v.push_back("272");
  v.push_back("1");
  v.push_back("145");
  v.push_back("1.0");
  v.push_back("146");
  v.push_back("1.0");
  v.push_back("273");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("");
  v.push_back("274");
  v.push_back("1");
  v.push_back("275");
  v.push_back("1");
  v.push_back("276");
  v.push_back("1");
  v.push_back(" 42");
  v.push_back("1.0");
  v.push_back(" 72");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("");
  v.push_back(" 73");
  v.push_back("1");
  v.push_back(" 74");
  v.push_back("1");
  v.push_back(" 75");
  v.push_back("1");
  v.push_back(" 94");
  v.push_back("63");
  v.push_back("  0");
  v.push_back("MATERIAL");
  v.push_back("  5");
  v.push_back("20");
  v.push_back("102");
  v.push_back("{ACAD_REACTORS");
  v.push_back("330");
  v.push_back("E");
  v.push_back("102");
  v.push_back("}");
  v.push_back("330");
  v.push_back("E");
  v.push_back("100");
  v.push_back("AcDbMaterial");
  v.push_back("  1");
  v.push_back("ByLayer");
  v.push_back("  2");
  v.push_back("");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back(" 40");
  v.push_back("1.0");
  v.push_back(" 71");
  v.push_back("1");
  v.push_back(" 41");
  v.push_back("1.0");
  v.push_back(" 91");
  v.push_back("-1023410177");
  v.push_back(" 42");
  v.push_back("1.0");
  v.push_back(" 72");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("");
  v.push_back(" 73");
  v.push_back("1");
  v.push_back(" 74");
  v.push_back("1");
  v.push_back(" 75");
  v.push_back("1");
  v.push_back(" 44");
  v.push_back("0.5");
  v.push_back(" 73");
  v.push_back("0");
  v.push_back(" 45");
  v.push_back("1.0");
  v.push_back(" 46");
  v.push_back("1.0");
  v.push_back(" 77");
  v.push_back("1");
  v.push_back("  4");
  v.push_back("");
  v.push_back(" 78");
  v.push_back("1");
  v.push_back(" 79");
  v.push_back("1");
  v.push_back("170");
  v.push_back("1");
  v.push_back(" 48");
  v.push_back("1.0");
  v.push_back("171");
  v.push_back("1");
  v.push_back("  6");
  v.push_back("");
  v.push_back("172");
  v.push_back("1");
  v.push_back("173");
  v.push_back("1");
  v.push_back("174");
  v.push_back("1");
  v.push_back("140");
  v.push_back("1.0");
  v.push_back("141");
  v.push_back("1.0");
  v.push_back("175");
  v.push_back("1");
  v.push_back("  7");
  v.push_back("");
  v.push_back("176");
  v.push_back("1");
  v.push_back("177");
  v.push_back("1");
  v.push_back("178");
  v.push_back("1");
  v.push_back("143");
  v.push_back("1.0");
  v.push_back("179");
  v.push_back("1");
  v.push_back("  8");
  v.push_back("");
  v.push_back("270");
  v.push_back("1");
  v.push_back("271");
  v.push_back("1");
  v.push_back("272");
  v.push_back("1");
  v.push_back("145");
  v.push_back("1.0");
  v.push_back("146");
  v.push_back("1.0");
  v.push_back("273");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("");
  v.push_back("274");
  v.push_back("1");
  v.push_back("275");
  v.push_back("1");
  v.push_back("276");
  v.push_back("1");
  v.push_back(" 42");
  v.push_back("1.0");
  v.push_back(" 72");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("");
  v.push_back(" 73");
  v.push_back("1");
  v.push_back(" 74");
  v.push_back("1");
  v.push_back(" 75");
  v.push_back("1");
  v.push_back(" 94");
  v.push_back("63");
  v.push_back("  0");
  v.push_back("MATERIAL");
  v.push_back("  5");
  v.push_back("21");
  v.push_back("102");
  v.push_back("{ACAD_REACTORS");
  v.push_back("330");
  v.push_back("E");
  v.push_back("102");
  v.push_back("}");
  v.push_back("330");
  v.push_back("E");
  v.push_back("100");
  v.push_back("AcDbMaterial");
  v.push_back("  1");
  v.push_back("Global");
  v.push_back("  2");
  v.push_back("");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back(" 40");
  v.push_back("1.0");
  v.push_back(" 71");
  v.push_back("1");
  v.push_back(" 41");
  v.push_back("1.0");
  v.push_back(" 91");
  v.push_back("-1023410177");
  v.push_back(" 42");
  v.push_back("1.0");
  v.push_back(" 72");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("");
  v.push_back(" 73");
  v.push_back("1");
  v.push_back(" 74");
  v.push_back("1");
  v.push_back(" 75");
  v.push_back("1");
  v.push_back(" 44");
  v.push_back("0.5");
  v.push_back(" 73");
  v.push_back("0");
  v.push_back(" 45");
  v.push_back("1.0");
  v.push_back(" 46");
  v.push_back("1.0");
  v.push_back(" 77");
  v.push_back("1");
  v.push_back("  4");
  v.push_back("");
  v.push_back(" 78");
  v.push_back("1");
  v.push_back(" 79");
  v.push_back("1");
  v.push_back("170");
  v.push_back("1");
  v.push_back(" 48");
  v.push_back("1.0");
  v.push_back("171");
  v.push_back("1");
  v.push_back("  6");
  v.push_back("");
  v.push_back("172");
  v.push_back("1");
  v.push_back("173");
  v.push_back("1");
  v.push_back("174");
  v.push_back("1");
  v.push_back("140");
  v.push_back("1.0");
  v.push_back("141");
  v.push_back("1.0");
  v.push_back("175");
  v.push_back("1");
  v.push_back("  7");
  v.push_back("");
  v.push_back("176");
  v.push_back("1");
  v.push_back("177");
  v.push_back("1");
  v.push_back("178");
  v.push_back("1");
  v.push_back("143");
  v.push_back("1.0");
  v.push_back("179");
  v.push_back("1");
  v.push_back("  8");
  v.push_back("");
  v.push_back("270");
  v.push_back("1");
  v.push_back("271");
  v.push_back("1");
  v.push_back("272");
  v.push_back("1");
  v.push_back("145");
  v.push_back("1.0");
  v.push_back("146");
  v.push_back("1.0");
  v.push_back("273");
  v.push_back("1");
  v.push_back("  9");
  v.push_back("");
  v.push_back("274");
  v.push_back("1");
  v.push_back("275");
  v.push_back("1");
  v.push_back("276");
  v.push_back("1");
  v.push_back(" 42");
  v.push_back("1.0");
  v.push_back(" 72");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("");
  v.push_back(" 73");
  v.push_back("1");
  v.push_back(" 74");
  v.push_back("1");
  v.push_back(" 75");
  v.push_back("1");
  v.push_back(" 94");
  v.push_back("63");
  v.push_back("  0");
  v.push_back("MLINESTYLE");
  v.push_back("  5");
  v.push_back("22");
  v.push_back("102");
  v.push_back("{ACAD_REACTORS");
  v.push_back("330");
  v.push_back("10");
  v.push_back("102");
  v.push_back("}");
  v.push_back("330");
  v.push_back("10");
  v.push_back("100");
  v.push_back("AcDbMlineStyle");
  v.push_back("  2");
  v.push_back("Standard");
  v.push_back(" 70");
  v.push_back("0");
  v.push_back("  3");
  v.push_back("");
  v.push_back(" 62");
  v.push_back("256");
  v.push_back(" 51");
  v.push_back("90.0");
  v.push_back(" 52");
  v.push_back("90.0");
  v.push_back(" 71");
  v.push_back("2");
  v.push_back(" 49");
  v.push_back("0.5");
  v.push_back(" 62");
  v.push_back("256");
  v.push_back("  6");
  v.push_back("BYLAYER");
  v.push_back(" 49");
  v.push_back("-0.5");
  v.push_back(" 62");
  v.push_back("256");
  v.push_back("  6");
  v.push_back("BYLAYER");
  v.push_back("  0");
  v.push_back("MLEADERSTYLE");
  v.push_back("  5");
  v.push_back("2C");
  v.push_back("102");
  v.push_back("{ACAD_REACTORS");
  v.push_back("330");
  v.push_back("F");
  v.push_back("102");
  v.push_back("}");
  v.push_back("330");
  v.push_back("F");
  v.push_back("100");
  v.push_back("AcDbMLeaderStyle");
  v.push_back("179");
  v.push_back("2");
  v.push_back("170");
  v.push_back("2");
  v.push_back("171");
  v.push_back("1");
  v.push_back("172");
  v.push_back("0");
  v.push_back(" 90");
  v.push_back("2");
  v.push_back(" 40");
  v.push_back("0.0");
  v.push_back(" 41");
  v.push_back("0.0");
  v.push_back("173");
  v.push_back("1");
  v.push_back(" 91");
  v.push_back("-1056964608");
  v.push_back(" 92");
  v.push_back("-2");
  v.push_back("290");
  v.push_back("1");
  v.push_back(" 42");
  v.push_back("2.0");
  v.push_back("291");
  v.push_back("1");
  v.push_back(" 43");
  v.push_back("8.0");
  v.push_back("  3");
  v.push_back("Standard");
  v.push_back(" 44");
  v.push_back("4.0");
  v.push_back("300");
  v.push_back("");
  v.push_back("342");
  v.push_back("29");
  v.push_back("174");
  v.push_back("1");
  v.push_back("175");
  v.push_back("1");
  v.push_back("176");
  v.push_back("0");
  v.push_back("178");
  v.push_back("1");
  v.push_back(" 93");
  v.push_back("-1056964608");
  v.push_back(" 45");
  v.push_back("4.0");
  v.push_back("292");
  v.push_back("0");
  v.push_back("297");
  v.push_back("0");
  v.push_back(" 46");
  v.push_back("4.0");
  v.push_back(" 94");
  v.push_back("-1056964608");
  v.push_back(" 47");
  v.push_back("1.0");
  v.push_back(" 49");
  v.push_back("1.0");
  v.push_back("140");
  v.push_back("1.0");
  v.push_back("294");
  v.push_back("1");
  v.push_back("141");
  v.push_back("0.0");
  v.push_back("177");
  v.push_back("0");
  v.push_back("142");
  v.push_back("1.0");
  v.push_back("295");
  v.push_back("0");
  v.push_back("296");
  v.push_back("0");
  v.push_back("143");
  v.push_back("3.75");
  v.push_back("271");
  v.push_back("0");
  v.push_back("272");
  v.push_back("9");
  v.push_back("273");
  v.push_back("9");
  v.push_back("  0");
  v.push_back("DICTIONARY");
  v.push_back("  5");
  v.push_back("2D");
  v.push_back("330");
  v.push_back("A");
  v.push_back("100");
  v.push_back("AcDbDictionary");
  v.push_back("280");
  v.push_back("1");
  v.push_back("281");
  v.push_back("1");
  v.push_back("  3");
  v.push_back("CREATED_BY_EZDXF");
  v.push_back("350");
  v.push_back("2E");
  v.push_back("  3");
  v.push_back("WRITTEN_BY_EZDXF");
  v.push_back("350");
  v.push_back("31");
  v.push_back("  0");
  v.push_back("DICTIONARYVAR");
  v.push_back("  5");
  v.push_back("2E");
  v.push_back("330");
  v.push_back("2D");
  v.push_back("100");
  v.push_back("DictionaryVariables");
  v.push_back("280");
  v.push_back("0");
  v.push_back("  1");
  v.push_back("1.4.3 @ 2026-08-12T10:02:26.972595+00:00");
  v.push_back("  0");
  v.push_back("DICTIONARYVAR");
  v.push_back("  5");
  v.push_back("31");
  v.push_back("330");
  v.push_back("2D");
  v.push_back("100");
  v.push_back("DictionaryVariables");
  v.push_back("280");
  v.push_back("0");
  v.push_back("  1");
  v.push_back("1.4.3 @ 2026-08-12T10:02:26.973142+00:00");
  v.push_back("  0");
  v.push_back("ENDSEC");
  v.push_back("  0");
  v.push_back("EOF");
  return v;
}();

std::string to_dxf(const Scene& scene, double scale, const std::string& mode) {
  std::map<std::string, std::tuple<int, int, int>> layer_colors;
  for (const auto& prim : scene.glb_primitives) {
    std::string l_name = sanitize_layer_name(prim.geom_name);
    if (layer_colors.find(l_name) == layer_colors.end()) {
      layer_colors[l_name] = get_prim_rgb(scene, prim);
    }
  }

  if (layer_colors.empty()) {
    layer_colors["0"] = {200, 200, 200};
  }

  // Every static handle in kHeaderStatic*/kObjectsStatic is well below
  // 0x691 - starting dynamic handles there (matching the reference file's
  // own first entity handle) keeps every handle in the file globally
  // unique.
  uint64_t handle_id = 0x691;
  auto next_handle = [&handle_id]() -> std::string {
    std::stringstream ss_h;
    ss_h << std::hex << std::uppercase << handle_id++;
    return ss_h.str();
  };

  std::map<std::string, std::string> layer_handles;
  for (const auto& [l_name, rgb] : layer_colors) {
    (void)rgb;
    layer_handles[l_name] = next_handle();
  }

  std::vector<std::string> lines = kHeaderStaticA;
  // LAYER table record count: built-in "0" + "Defpoints" + this scene's layers.
  lines.push_back(std::to_string(layer_colors.size() + 2));
  lines.insert(lines.end(), kHeaderStaticB.begin(), kHeaderStaticB.end());

  for (const auto& [l_name, rgb] : layer_colors) {
    auto [lr, lg, lb] = rgb;
    int aci = rgb_to_aci(lr, lg, lb);
    // Group 420 (24-bit true color) is an R2004+ addition - real ezdxf
    // never emits it for an R2000/AC1015 document, so it's dropped here
    // too; ACI (62) is the only color mechanism R2000 actually supports.
    // 370/390 (lineweight, plot style handle) are required on every LAYER
    // record once the drawing uses a Named plot style table - AutoCAD
    // desktop rejects the whole TABLES section ("Did not receive
    // PlotStyleName") if any layer omits them.
    lines.push_back("  0");
    lines.push_back("LAYER");
    lines.push_back("  5");
    lines.push_back(layer_handles[l_name]);
    lines.push_back("330");
    lines.push_back("1");
    lines.push_back("100");
    lines.push_back("AcDbSymbolTableRecord");
    lines.push_back("100");
    lines.push_back("AcDbLayerTableRecord");
    lines.push_back("  2");
    lines.push_back(l_name);
    lines.push_back(" 70");
    lines.push_back("0");
    lines.push_back(" 62");
    lines.push_back(std::to_string(aci));
    lines.push_back("  6");
    lines.push_back("Continuous");
    lines.push_back("370");
    lines.push_back("-3");
    lines.push_back("390");
    lines.push_back("13");
  }

  lines.insert(lines.end(), kHeaderStaticC.begin(), kHeaderStaticC.end());
  lines.push_back("  0");
  lines.push_back("SECTION");
  lines.push_back("  2");
  lines.push_back("ENTITIES");

  std::ostringstream num;
  num << std::fixed << std::setprecision(6);
  auto fmt6 = [&num](double v) -> std::string {
    num.str("");
    num.clear();
    num << v;
    return num.str();
  };

  for (const auto& prim : scene.glb_primitives) {
    std::string l_name = sanitize_layer_name(prim.geom_name);
    size_t tri_count = prim.indices.size() / 3;
    if (tri_count == 0) continue;

    auto [pr, pg, pb] = get_prim_rgb(scene, prim);
    int aci = rgb_to_aci(pr, pg, pb);

    if (mode == "polyface") {
      // Structure verified against real ezdxf's own render_polyface()
      // output byte-for-byte, not guessed: face-record VERTEX entries
      // carry a color (62) and dummy 0/0/0 coordinates but NOT the
      // AcDbVertex subclass marker that point-vertex entries have, and
      // SEQEND's owner (330) is the POLYLINE's own handle, not
      // Model_Space's - both were wrong here before and are exactly why
      // AutoCAD desktop rejected polyface-mode output while accepting
      // 3dface-mode output using the same scaffold.
      std::size_t vert_count = prim.positions.size() / 3;
      std::string polyline_handle = next_handle();

      lines.push_back("  0");
      lines.push_back("POLYLINE");
      lines.push_back("  5");
      lines.push_back(polyline_handle);
      lines.push_back("330");
      lines.push_back("17");
      lines.push_back("100");
      lines.push_back("AcDbEntity");
      lines.push_back("  8");
      lines.push_back(l_name);
      lines.push_back(" 62");
      lines.push_back(std::to_string(aci));
      lines.push_back("100");
      lines.push_back("AcDbPolyFaceMesh");
      lines.push_back(" 66");
      lines.push_back("1");
      lines.push_back(" 10");
      lines.push_back("0.0");
      lines.push_back(" 20");
      lines.push_back("0.0");
      lines.push_back(" 30");
      lines.push_back("0.0");
      lines.push_back(" 70");
      lines.push_back("64");
      lines.push_back(" 71");
      lines.push_back(std::to_string(vert_count));
      lines.push_back(" 72");
      lines.push_back(std::to_string(tri_count));

      for (std::size_t i = 0; i < vert_count; ++i) {
        double vx = prim.positions[i * 3] * scale;
        double vy = prim.positions[i * 3 + 1] * scale;
        double vz = prim.positions[i * 3 + 2] * scale;
        lines.push_back("  0");
        lines.push_back("VERTEX");
        lines.push_back("  5");
        lines.push_back(next_handle());
        lines.push_back("330");
        lines.push_back("17");
        lines.push_back("100");
        lines.push_back("AcDbEntity");
        lines.push_back("  8");
        lines.push_back(l_name);
        lines.push_back("100");
        lines.push_back("AcDbVertex");
        lines.push_back("100");
        lines.push_back("AcDbPolyFaceMeshVertex");
        lines.push_back(" 10");
        lines.push_back(fmt6(vx));
        lines.push_back(" 20");
        lines.push_back(fmt6(vy));
        lines.push_back(" 30");
        lines.push_back(fmt6(vz));
        lines.push_back(" 70");
        lines.push_back("192");
      }

      for (std::size_t i = 0; i < tri_count; ++i) {
        std::string idx0 = std::to_string(prim.indices[i * 3] + 1);
        std::string idx1 = std::to_string(prim.indices[i * 3 + 1] + 1);
        std::string idx2 = std::to_string(prim.indices[i * 3 + 2] + 1);
        lines.push_back("  0");
        lines.push_back("VERTEX");
        lines.push_back("  5");
        lines.push_back(next_handle());
        lines.push_back("330");
        lines.push_back("17");
        lines.push_back("100");
        lines.push_back("AcDbEntity");
        lines.push_back("  8");
        lines.push_back(l_name);
        lines.push_back(" 62");
        lines.push_back(std::to_string(aci));
        lines.push_back("100");
        lines.push_back("AcDbFaceRecord");
        lines.push_back(" 10");
        lines.push_back("0.0");
        lines.push_back(" 20");
        lines.push_back("0.0");
        lines.push_back(" 30");
        lines.push_back("0.0");
        lines.push_back(" 70");
        lines.push_back("128");
        lines.push_back(" 71");
        lines.push_back(idx0);
        lines.push_back(" 72");
        lines.push_back(idx1);
        lines.push_back(" 73");
        lines.push_back(idx2);
      }

      lines.push_back("  0");
      lines.push_back("SEQEND");
      lines.push_back("  5");
      lines.push_back(next_handle());
      lines.push_back("330");
      lines.push_back(polyline_handle);
      lines.push_back("100");
      lines.push_back("AcDbEntity");
      lines.push_back("  8");
      lines.push_back(l_name);
      continue;
    }

    for (size_t i = 0; i < tri_count; ++i) {
      uint32_t i0 = prim.indices[i * 3];
      uint32_t i1 = prim.indices[i * 3 + 1];
      uint32_t i2 = prim.indices[i * 3 + 2];

      std::string v0x = fmt6(prim.positions[i0 * 3] * scale);
      std::string v0y = fmt6(prim.positions[i0 * 3 + 1] * scale);
      std::string v0z = fmt6(prim.positions[i0 * 3 + 2] * scale);

      std::string v1x = fmt6(prim.positions[i1 * 3] * scale);
      std::string v1y = fmt6(prim.positions[i1 * 3 + 1] * scale);
      std::string v1z = fmt6(prim.positions[i1 * 3 + 2] * scale);

      std::string v2x = fmt6(prim.positions[i2 * 3] * scale);
      std::string v2y = fmt6(prim.positions[i2 * 3 + 1] * scale);
      std::string v2z = fmt6(prim.positions[i2 * 3 + 2] * scale);

      lines.push_back("  0");
      lines.push_back("3DFACE");
      lines.push_back("  5");
      lines.push_back(next_handle());
      lines.push_back("330");
      lines.push_back("17");
      lines.push_back("100");
      lines.push_back("AcDbEntity");
      lines.push_back("  8");
      lines.push_back(l_name);
      lines.push_back(" 62");
      lines.push_back(std::to_string(aci));
      lines.push_back("100");
      lines.push_back("AcDbFace");
      lines.push_back(" 10");
      lines.push_back(v0x);
      lines.push_back(" 20");
      lines.push_back(v0y);
      lines.push_back(" 30");
      lines.push_back(v0z);
      lines.push_back(" 11");
      lines.push_back(v1x);
      lines.push_back(" 21");
      lines.push_back(v1y);
      lines.push_back(" 31");
      lines.push_back(v1z);
      lines.push_back(" 12");
      lines.push_back(v2x);
      lines.push_back(" 22");
      lines.push_back(v2y);
      lines.push_back(" 32");
      lines.push_back(v2z);
      lines.push_back(" 13");
      lines.push_back(v2x);
      lines.push_back(" 23");
      lines.push_back(v2y);
      lines.push_back(" 33");
      lines.push_back(v2z);
    }
  }

  lines.push_back("  0");
  lines.push_back("ENDSEC");
  lines.insert(lines.end(), kObjectsStatic.begin(), kObjectsStatic.end());

  std::string text;
  for (std::size_t i = 0; i < lines.size(); ++i) {
    text += lines[i];
    text += "\r\n";
  }

  std::stringstream hs_stream;
  hs_stream << std::hex << std::uppercase << (handle_id + 0x10);
  std::string handseed_str = hs_stream.str();
  std::size_t pos = text.find("__HANDSEED__");
  if (pos != std::string::npos) {
    text.replace(pos, 12, handseed_str);
  }
  return text;
}

void export_dxf(const Scene& scene, const std::filesystem::path& path, double scale,
                const std::string& mode) {
  std::filesystem::create_directories(path.parent_path());
  std::string content = to_dxf(scene, scale, mode);
  std::ofstream file(path, std::ios::binary);
  if (!file.is_open()) {
    throw std::runtime_error("Failed to open output file: " + path.string());
  }
  file.write(content.data(), content.size());
}

}  // namespace openskp
