name: Android

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:


  # Android(aarch64) build
  build-android:

    runs-on: ubuntu-latest
    name: Build for Android(arm64v8a)
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Show android sdk root
        run: |
            env | grep ANDROID
            echo $ANDROID_SDK_ROOT
      - name: Setup
        run: |
            sudo apt-get install -y ninja-build tree
      - name: Show android sdk details
        run: |
            tree $ANDROID_SDK_ROOT
      - name: CmakeAndBuild
        run: |
            ./scripts/bootstrap-android-cmake-linux.sh
            cd build-android
            ninja -v

