/*
---------------------------------------------------------------------------
Open Asset Import Library (assimp)
---------------------------------------------------------------------------

Copyright (c) 2006-2026, assimp team

All rights reserved.

Redistribution and use of this software in source and binary forms,
with or without modification, are permitted provided that the following
conditions are met:

* Redistributions of source code must retain the above
copyright notice, this list of conditions and the
following disclaimer.

* Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the
following disclaimer in the documentation and/or other
materials provided with the distribution.

* Neither the name of the assimp team, nor the names of its
contributors may be used to endorse or promote products
derived from this software without specific prior
written permission of the assimp team.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
---------------------------------------------------------------------------
*/

#include "AbstractImportExportBase.h"
#include "UnitTestPCH.h"

#include <assimp/postprocess.h>
#include <assimp/scene.h>
#include <assimp/Importer.hpp>

using namespace Assimp;

class utSkpImportExport : public AbstractImportExportBase {
public:
    bool importerTest() override {
        Assimp::Importer importer;
        const aiScene *scene = importer.ReadFile(ASSIMP_TEST_MODELS_DIR "/SKP/cube.skp", aiProcess_ValidateDataStructure);
#ifndef ASSIMP_BUILD_NO_SKP_IMPORTER
        return nullptr != scene;
#else
        return nullptr == scene;
#endif // ASSIMP_BUILD_NO_SKP_IMPORTER
    }
};

TEST_F(utSkpImportExport, importSkpFromFileTest) {
    EXPECT_TRUE(importerTest());
}

#ifndef ASSIMP_BUILD_NO_SKP_IMPORTER
// cube.skp: a single untextured six-face box at the root level, generated by
// OpenSKP's own writer (see the PR description for how) - no real SketchUp
// file involved. Locks the basic geometry/material shape this importer
// produces, not just that ReadFile() returns non-null.
TEST_F(utSkpImportExport, cubeHasExpectedGeometryAndMaterials) {
    Assimp::Importer importer;
    const aiScene *scene = importer.ReadFile(ASSIMP_TEST_MODELS_DIR "/SKP/cube.skp", aiProcess_ValidateDataStructure);
    ASSERT_NE(nullptr, scene);
    EXPECT_GT(scene->mNumMeshes, 0u);
    EXPECT_GT(scene->mNumMaterials, 0u);
    ASSERT_NE(nullptr, scene->mRootNode);

    for (unsigned int i = 0; i < scene->mNumMeshes; ++i) {
        const aiMesh *mesh = scene->mMeshes[i];
        EXPECT_GT(mesh->mNumVertices, 0u);
        EXPECT_GT(mesh->mNumFaces, 0u);
        EXPECT_TRUE(mesh->HasNormals());
        EXPECT_LT(mesh->mMaterialIndex, scene->mNumMaterials);
        for (unsigned int f = 0; f < mesh->mNumFaces; ++f) {
            EXPECT_EQ(3u, mesh->mFaces[f].mNumIndices); // every OpenSKP-emitted face is a triangle
        }
    }
}

// textured_instances.skp: one component definition (a textured quad) placed
// twice at different positions - exercises the mesh-sharing/instancing path
// (multiple aiNodes referencing the same aiMesh indices) and the embedded
// texture path together.
TEST_F(utSkpImportExport, placesTheSameDefinitionTwiceAsSharedMeshIndices) {
    Assimp::Importer importer;
    const aiScene *scene = importer.ReadFile(
            ASSIMP_TEST_MODELS_DIR "/SKP/textured_instances.skp", aiProcess_ValidateDataStructure);
    ASSERT_NE(nullptr, scene);
    EXPECT_GT(scene->mNumTextures, 0u);

    ASSERT_NE(nullptr, scene->mRootNode);
    ASSERT_EQ(2u, scene->mRootNode->mNumChildren);
    aiNode *a = scene->mRootNode->mChildren[0];
    aiNode *b = scene->mRootNode->mChildren[1];
    ASSERT_GT(a->mNumMeshes, 0u);
    ASSERT_EQ(a->mNumMeshes, b->mNumMeshes);
    // Same definition placed twice -> both nodes reference the identical set
    // of underlying aiMesh indices (assimp's own instancing convention).
    for (unsigned int i = 0; i < a->mNumMeshes; ++i) {
        EXPECT_EQ(a->mMeshes[i], b->mMeshes[i]);
    }
    // ...but at different positions.
    EXPECT_NE(a->mTransformation.a4, b->mTransformation.a4);
}
#endif // ASSIMP_BUILD_NO_SKP_IMPORTER
