name: iosdevice

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'build'
        run: ./port/iOS/build-lightweight.sh iphone
      - uses: actions/upload-artifact@v1
        with:
          name: assimp-iosdevice
          path: '${{ runner.workspace }}/lib/libassimprelease.a'
      - uses: actions/upload-artifact@v1
        with:
          name: irrxml-iosdevice
          path: '${{ runner.workspace }}/lib/libirrxmlrelease.a'

