name: iosdevice

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'build'
        run: ./port/iOS/build.sh --stdlib=libc++ --archs="armv7 armv7s arm64 arm64e" --sourcedir="./"
      #- uses: actions/upload-artifact@v1
      #  with:
      #    name: assimp-osxuniversal
      #    path: '${{ runner.workspace }}/build/osx/bin/libassimp.dylib' #'/Users/runner/runners/2.165.2/work/assimp/build/osx/bin/libassimp.dylib'
