name: iossimulator

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'build'
        run: ./port/iOS/build-lightweight.sh simulator
      - uses: actions/upload-artifact@v1
        with:
          name: assimp
          path: '${{ runner.workspace }}/assimp/lib/libassimpdebug.a'
      - uses: actions/upload-artifact@v1
        with:
          name: irrxml
          path: '${{ runner.workspace }}/assimp/lib/libirrxmldebug.a'
